### ISSUE TITLE
cat deps/exrm/mix.exs does not exist, but it actually does

### ISSUE THREAD

**Issue by Gacnt** [boldpoker/edeliver#107]
I'm trying to deploy, it gets most of the way then fails:
```
-----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
-----> Pushing new commits with git to: xxx@xxx
-----> Resetting remote hosts to xxxxxxxxxxxx
-----> Cleaning generated files from last build
-----> Fetching / Updating dependencies
-----> Compiling sources
-----> Detecting exrm version
cat: deps/exrm/mix.exs: No such file or directory

Failed to detect exrm version.

Please set EXRM_VERSION_MAJOR, EXRM_VERSION_MINOR and EXRM_VERSION_PATCH
in the console or the config file.

Detected '' as major,
         '' as minor
     and '' as patch version.
```

I do have `exrm` in my packages, and it is `mix deps.get, compile` so I'm not sure how to fix this issue.

If I `cat: deps/exrm/mix.exs` I do get the output of the file, so I know it exists

**Comment by rstacruz** [comment]
I'm getting this as well. Build host is Ubuntu on Amazon EC2, deploying from my local OSX 10.11.

**Comment by rstacruz** [comment]
I see what happened. I was working on a branch. By default, edeliver works on `master`. use `--branch=<branch name>`.

**Comment by Frost** [comment]
This happened to me because I didn't have `exrm` listed as one of my dependencies in my `mix.exs`.

I found [this article](https://www.alexfilatov.com/2016/05/02/cat-depsexrmmix-exs-no-such-file-or-directory-on-edeliver-build-host/) that mentions this.

The reason it says that `deps/exrm/mix.exs` does not exists is because it does not exist on the build server.

Adding `exrm` in `mix.exs` and `:exrm` in the applications list seems to solve this problem.

**Comment by bharendt** [comment]
It is recommended, that `exrm` or `distillery` is added as dependency to the project which should be deployed as release using `edeliver`. It is not required to include `exrm` or `distillery` as application into the release, but it is recommended to include `edeliver` as application. This provides extended functionality for maintenance of the releases, like displaying versions, migrations, synchronous start etc. As @rstacruz already mentioned, edeliver builds the master branch by default unless the `--branch=<...>` option is passed. Keep that in mind when you build and deploy the first release and when you try the deployment the first time in a new branch.

**Comment by balena** [comment]
`edeliver` 1.4.2 does not work with `distillery` at all. Maybe the case is fixed in `master`, but I couldn't make it work. If you use `exrm`, it works.

**Comment by denispeplin** [comment]
I'm using `distillery`, but Edelivery demands `exrm` presence during `mix edelivery update`.
I'm getting same error, `cat: deps/exrm/mix.exs: No such file or directory`.
