### ISSUE TITLE
version command fails

### ISSUE THREAD

**Issue by dustinfarris** [boldpoker/edeliver#110]
I am getting a weird failure when i try to detect the version

```
└──➤ mix edeliver version

EDELIVER EXAMPLE WITH VERSION COMMAND

-----> getting release versions from staging servers

staging node:

  user    : web
  host    : stage.app.industrymaps.com
  path    : /var/web
  response: RPC to 'example@stage-industrymaps-app' failed: {'EXIT',
                                                 {undef,
                                                  [{'Elixir.Edeliver',
                                                    run_command,
                                                    [[release_version,
                                                      example]],
                                                    []},
                                                   {rpc,
                                                    '-handle_call_call/6-fun-0-',
                                                    5,
                                                    [{file,rpc.erl},
                                                     {line,206}]}]}}

VERSION DONE!
```

**Comment by dustinfarris** [comment]
Also, which_applications does not show my application on the server

```
iex(1)> :application.which_applications
[{:logger, 'logger', '1.2.6'}, {:iex, 'iex', '1.2.6'},
 {:elixir, 'elixir', '1.2.6'}, {:compiler, 'ERTS  CXC 138 10', '6.0.3'},
 {:stdlib, 'ERTS  CXC 138 10', '2.8'}, {:kernel, 'ERTS  CXC 138 10', '4.2'}]
```

**Comment by dustinfarris** [comment]
Trying to see current release exits:

```
iex(2)> :release_handler.which_releases(:current)
** (exit) exited in: :gen_server.call(:release_handler, :which_releases, :infinity)
    ** (EXIT) no process
    (stdlib) gen_server.erl:212: :gen_server.call/3
             release_handler.erl:343: :release_handler.which_releases/1
```

**Comment by bharendt** [comment]
Did you add `edeliver` to the `applications` section in the mix file? This is required to include it into the release, e.g. like this:

```elixir
# mix.exs
def application do
  [
    mod: {..., []},
    applications: [

      ...,
      edeliver 
    ]
  ]
end
```
Edeliver should be added as last application to be able to monitor whether the start of the release was successful. Your application should be included actually automatically.

**Comment by bharendt** [comment]
How did you start the release? The output you pasted here ("`iex(2)>`") does not look like a release is running. It should actually show the node name at this place.

**Comment by dustinfarris** [comment]
i started with `mix edeliver start`, it is running in `ps ax` ...  I had added :edeliver to applications but forgot to commit, I am trying a new release now to see if that works.

**Comment by dustinfarris** [comment]
That did not work.  I am still getting the same error from `mix edeliver version`

**Comment by dustinfarris** [comment]
Ohh.. i had to restart.  It is working now.  Thanks!

**Comment by bigardone** [comment]
Hi @bharendt 
And how do you set it in an umbrella project? In every mix file of the apps?
Thanks in advance

**Comment by msambarino** [comment]
> Hi @bharendt
And how do you set it in an umbrella project? In every mix file of the apps?
Thanks in advance

this. i cant seem to get it to work in an umbrella project, any help is appreciated.

Thanks
