### ISSUE TITLE
About start beam in privileges port when use a non-privileged user

### ISSUE THREAD

**Issue by developerworks** [boldpoker/edeliver#114]
I wanna start a elixir tcp server that listen on port 443 with a non-privileged user, i run the following command to allow it listen on a privileged port.

```
setcap CAP_NET_BIND_SERVICE=+eip /srv/erlang/erts-7.3/bin/beam.smp
```
How i can execute the command before restart my server, after upload and deploy the new release. Is there any hook can be used at the stage.

I use this command to deploy to production server
```
mix edeliver update production --branch=master --start-deploy --verbose --to=0.1.39
```

**Comment by bharendt** [comment]
Added `pre_start_deployed_release` hook and the corresponding post hook. Hope that helps.
