### ISSUE TITLE
Where to configure an alternative identity file for SSH?

### ISSUE THREAD

**Issue by mfeckie** [boldpoker/edeliver#117]
Let's say we're deploying to and EC2 instance and need to use our `.pem` file when connecting.  Ordinarily we can pass this with the `-i` flag to ssh.  I can't see a straightforward way to do this with edeliver.

Any ideas on how to achieve this?

**Comment by bharendt** [comment]
You could add the identity file which should be used for that host to your `~/.ssh/config` like this:

```txt
Host your.ec2.instance.com
  IdentityFile ~/.ssh/ec2_id_dsa
```

The drawback is, that this needs to be done on each developer machine which should be able to deploy to that host.

I think we could add an edeliver option which can set the `-F <configfile>` ssh option to be able to set ssh options in a separate config file which could be checked in into the project repository.

**Comment by mfeckie** [comment]
Thanks, using ssh config is fine for now

**Comment by route** [comment]
@bharendt did you you have a chance to add it? This is exactly the reason for me when I use edeliver with bastion host and private network inside. Just didn't want to pollute global config

**Comment by shymega** [comment]
I'd like to second my support for an option to specify a SSH config file. I'm trying to use my `~/.ssh/config` file, but its specific to my workstation, and it makes deployment of my OTP (Elixir) application difficult across many different workstations. Thanks :smile:

**Comment by shymega** [comment]
just an idea: what if `ssh` parameters could be redefined/defined in the `.deliver/config` file instead? 

That way it can be on a per-repository basis, and it can work without defining another command line argument.. or both could be done.

**Comment by njwest** [comment]
Defining SSH params in .deliver/config seems like a really maintainable option, as @shymega suggests...
