### ISSUE TITLE
How do you get the environment variables of the user during deployment?

### ISSUE THREAD

**Issue by taktran** [boldpoker/edeliver#118]
My build is failing because I'm trying to get the environment variables on the build machine using `System.get_env('SOME_ENV_VAR')` in my `prod.exs` file. However, it returns `nil` when the edeliver ssh agent is running during the update dependencies step.

This is the error I was getting (I'm doing `String.to_integer(System.get_env('SOME_VAR'))` on the offending line):

```
-----> Fetching / Updating dependencies
stdin: is not a tty
using mix to fetch and update deps
rebar and rebar3 for mix was built already
warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
** (Mix.Config.LoadError) could not load config config/prod.exs
    ** (ArgumentError) argument error
    :erlang.binary_to_integer(nil)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:236: :erl_eval.expr/5
    (stdlib) erl_eval.erl:228: :erl_eval.expr/5
    (stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:236: :erl_eval.expr/5
    (stdlib) erl_eval.erl:228: :erl_eval.expr/5
```

I know the variable is missing because I ran `env` in the `pre_erlang_get_and_update_deps` step, and it was missing the variable. I ssh'd into the machine and did `env` to check that they were there for the build user.

Is there a way to get the variables during build/deployment?

I'm not sure if it is related, but I have had this situation when I've had to run `sudo [cmd]`, and to fix it, I've done `sudo -E [cmd]` so that I have the environment variables of the user. Is edeliver using sudo?

**Comment by bharendt** [comment]
edeliver sources the `~/.profile` on the build and on the deploy hosts. If you want to set `SOME_ENV_VAR` for the build process you can set it in that file on the build host and it would be available for the build process. Passing `SOME_ENV_VAR` to the edeliver build command has no effect on the build machine.

**Comment by taktran** [comment]
Ok thanks. Adding the env in `~/.profile` works for now.
