### ISSUE TITLE
Error running edeliver

### ISSUE THREAD

**Issue by OvermindDL1** [boldpoker/edeliver#120]
Got an error trying to integrate edeliver into a large project, ended up just putting it into a brand new otherwise empty project with same error.

Via a bash shell I get:
```bash
$ mix edeliver
'deps' is not recognized as an internal or external command,
operable program or batch file.
```
For some reason even this basic command is trying to launch a windows command prompt, even though a multitude of bash shells are installed (as well as SSH client and server and everything else needed).

The `exrm` library works wonderfully on Windows (yes I know) and `edeliver` seems to have code to support windows as seen via https://github.com/boldpoker/edeliver/blob/master/lib/mix/tasks/edeliver.ex#L115-121 and yet it seems to be trying to launch a windows command prompt, which may work except for the fact that the path joining at https://github.com/boldpoker/edeliver/blob/master/lib/mix/tasks/edeliver.ex#L66 is causing issues by giving / instead of \.

Considering exrm has wonderful support for Windows (ick) and edeliver is built on exrm, any chance on getting Windows support for edeliver?  Via SSH is fine (or the windows network would be more 'usual' I guess).

**Comment by bharendt** [comment]
Using edeliver directly on windows is not supported. It might be that it runs in the ubuntu bash shell on windows or you can run edeliver in a docker [container](https://github.com/nviennot/edeliver-build-docker/blob/master/Dockerfile).

**Comment by OvermindDL1** [comment]
I've actually been using a docker container in Windows for about a month now and it works well with this!

I'd recommend adding that as a suggestion for 'Windows support' to the README.md with a basic example.  :-)

**Comment by bharendt** [comment]
Yes, we can add that to the readme or as a wiki page. Feel free to add more information here how your setup is, which docker file or docker container you are using and how you run the edeliver  commands in the container.

**Comment by OvermindDL1** [comment]
I have a few docker containers, one is a build server that is building those for ubuntu 16.04.  If a tag is pushed than that version also gets edelivered out to another container (and later to a production server).  Fairly simple generic build setup.  But docker lets it run on Windows.  For the current production server we still have to compile with exrm on the Windows host (the production server hosts the elixir/erlang application as a windows service), but we should only need to be doing that for a few more months to a year tops.

**Comment by AlchemistCamp** [comment]
It really is a shame `edeliver` breaks the cross-platform support `exrm` offers. This kind of thing makes the Elixir ecosystem a bit more hostile to Windows users, especially newbies.

Not everybody learning a programming language is going to want to buy an expensive mac or install linux on a VM. Many will just give up and choose a different language, echoing what happened with Ruby last decade.

**Comment by lessless** [comment]
@AlchemistCamp @bharendt and other contributors did a wonderful job putting this tool together and using words such as "shame" is inappropriate here.
I would personally love to see a Windows support and it may not be that hard to actually implement, especially considering that this is open-source project and PRs are always welcome. 

Not to mention that Exrm is a deprecated tool which support will be removed in the next version.

**Comment by AlchemistCamp** [comment]
@lessless 

Each tool that becomes accepted as a standard part of the Elixir ecosystem that simply closes breaking bugs on Windows makes the language less approachable to Windows users, which makes the ecosystem more of a monoculture, which leads to more new projects that break the cross-platform aspect of pieces they build upon, which leads to another loop in the same vicious circle, and ultimately to a much smaller Elixir community and fewer libraries of everything.

I'm sorry you believe it's inappropriate to say that it's a shame. Here's another way of putting it: "it is a situation which causes sadness, from the standpoint of those who would like to see the language grow".

I don't want to get into a big debate about it and I _definitely_ don't want to detract from the sacrifices that go into writing OSS. I'm just pointing out pain points when I encounter them in the course of making screencasts for Elixir learners. If there's nothing new or useful in my comment, feel free to disregard.

**Comment by lessless** [comment]
@AlchemistCamp English is my second language and I read it as people who build Edeliver should be ashamed that they didn't add Windows support. Correct me if I'm wrong please. 
From resources standpoint I can definitely tell that adding Windows support is not a priority in the observable future since there are bugs in already existing flow and there is a housekeeping to do. 
Also neither me or @johannesE  uses Windows afaik, so it's a double bump.
On the other hand **introducing** Windows support should be pretty easy thanks to the Edeliver's modular architecture. If there will be anyone wishing to tackle the problem and carry on maintenance of the supplied solution I'm willing to sit down together and put a plan for it. 

Ensuring Elixir's stable growth is our common goal, so yeah - why not Windows? :)

**Comment by AlchemistCamp** [comment]
Oh, I understand! "It's a shame" is a set phrase that means something is
unfortunate, but has no meaning at all that someone should feel ashamed.
E.g, "It's a shame it started raining during the barbeque."

**Comment by lessless** [comment]
Ha, thanks for clarification and sorry for confusion. Again, as soon as there will be anyone willing to tackle it I'm sure he will get any needed support.
Just for the history - what do you think is more important: being able to run edeliver commands on a Windows machine or to build a release on Windows?

**Comment by johannesE** [comment]
+1 Anyone trying to tackle windows support has our full support.

@OvermindDL1 I know it's been a while, but would you be willing to provide that basic docker example you talked about? You can also provide it here if that's what you prefer. I will then add it to the wiki.

**Comment by AlchemistCamp** [comment]
I think running the commands is more important. People deploying to Linux
servers from Windows home machines had got to be more common than the
reverse.

**Comment by OvermindDL1** [comment]
> @OvermindDL1 I know it's been a while, but would you be willing to provide that basic docker example you talked about? You can also provide it here if that's what you prefer. I will then add it to the wiki.

Heh, as stated in my last post we were only expecting to use windows for a short period more, and we've long since transitioned to  pure linux at this point with Distillery.  Honestly I'm not actually sure what edeliver would be useful for in our setup as I have a simple shell script that just builds the release (and grabbing dependencies and generating the phoenix digest and so forth), then rsync's the release to the machines, then sends an ssh command to each machine to restart the systemd service of the elixir server so as to perform the update one at a time (stopping if any failures).  It's just a couple of lines of shell so...  ^.^;

**Comment by chavenor** [comment]
@OvermindDL1 I read everything over I'm coding on Windows and want to push to a Linux box in the cloud.   Is this currently possible?

**Comment by OvermindDL1** [comment]
Use docker, the beam needs to be compiled for the same arch that it will be deployed to.

**Comment by OvermindDL1** [comment]
I'm using a RHEL docker image base from https://access.redhat.com/containers/ as a start, you need an active RHEL subscription for it.  Remember, whatever you run on needs to be compiled on the same setup.  There are some user made ones like https://hub.docker.com/r/lionelman45/rhel7/ but you still need an active RHEL repository subscription.  Here's a basic how-to for RHEL:  http://cloudgeekz.com/625/howto-create-a-docker-image-for-rhel.html

Overall, I'd say if you can run it within docker for production as well, you should, you can use much better containers and compiling and all that work is so much easier when docker is used through-out rather than what I'm doing.

**Comment by tporto** [comment]
> 
> 
> Just choose a docker image that matches the platform you are deploying to, so what is that?

My problem is deploying with edeliver via docker, it does not find the remote server, already passed the keys and does not connect.

**Comment by OvermindDL1** [comment]
If it doesn't find the remote server that's an entirely different issue, are you able to ssh to the remote server from within your docker build/deploy image?

**Comment by tporto** [comment]
> 
> 
> If it doesn't find the remote server that's an entirely different issue, are you able to ssh to the remote server from within your docker build/deploy image?

It accesses, but does not match with sshkey, so this ties edeliver to connect.

**Comment by OvermindDL1** [comment]
> Error: Ensuring hosts are ready to accept git pushes

Uh, git?  Where's that coming up?

**Comment by typedefstructer** [comment]
can anyone point me to how I can add support to windows, I'll be happy to do it
