### ISSUE TITLE
Hot code upgrade fails

### ISSUE THREAD

**Issue by net** [boldpoker/edeliver#123]
I'm trying to perform a hot code upgrade to `1.0.4+15-b6f1b64` from `1.0.3+13-9afc49f`.

I generated the upgrade successfully with `mix edeliver build upgrade --from=v1.0.3 --to=v1.0.4`, but when I run `mix edeliver deploy upgrade to production` I get:
```
-----> Upgrading release to 1.0.4+15-b6f1b64
Release 1.0.4+15-b6f1b64 is already unpacked, now installing.
Generating vm.args/sys.config for upgrade...
sys.config ready!
vm.args ready!
Release 1.0.4+15-b6f1b64 is already unpacked, now installing.
ERROR: release_handler:check_install_release failed: {no_matching_relup,
                                                      "1.0.4+15-b6f1b64",
                                                      "1.0.3+13-9afc49f"}

A remote command failed on:
```

I'm not sure what steps I can take to troubleshoot/fix this problem. Normal upgrades (`mix edeliver deploy release to production`, restart server) work fine.

**Comment by net** [comment]
It turns out the auto-versioning (`+15-b6f1b64`) was causing the issues. I removed them and hot code upgrades work now.

Perhaps the git tags are required to strictly match the version numbers?

**Comment by bharendt** [comment]
Thanks for the report. Do you still have the upgrade tar which failed to deploy? It would be quite helpful if you could check whether the following file was included at that correct path:

```
  releases/1.0.4+15-b6f1b64/relup
```

and whether the [relup file](http://erlang.org/doc/man/relup.html#id76657) contained the correct versions, like:

```erlang
{"1.0.4+15-b6f1b64",
  [{"1.0.3+13-9afc49f", Descr, Instructions}, ...],
  [{"1.0.3+13-9afc49f", Instructions}, ...]}.

```

**Comment by net** [comment]
Unfortunately I do not. I'll generate one later and check.

**Comment by bharendt** [comment]
Thanks! I will also try to reproduce it, but it might take some time. Usually it is recommended to build an upgrad from an existing old release, using the `--with=<version>` option. Building the old release again (using the `--from=<tag/git-hash>`) is actually only a fallback, if the running release (tar) is lost.

**Comment by bharendt** [comment]
Replacing this issue with #142. Building the old release from sources (which is required to build the live upgrade) will be obsolete and the data of the running release will be used to build the upgrade.
