### ISSUE TITLE
Under FreeBSD, command is put into the background when redirected to /dev/null

### ISSUE THREAD

**Issue by kuon** [boldpoker/edeliver#124]
For example, under FreeBSD the following code:

      git init &> /dev/null
      git config receive.denyCurrentBranch ignore

Will put `git init` into the background, and execute `git config` first, which will fail because the repository has not been created yet.

Using FreeBSD 10.3

**Comment by kuon** [comment]
After investigating a bit, I think it's because `sh` is the default shell under FreeBSD.

Maybe wrapping the command into a `bash -c` in `__sync_remote` would resolve the issue.

**Comment by bharendt** [comment]
Thanks for investigating this. Yes, edeliver requires (only) bash or zsh to be available on the deploy hosts but also to be the default shell for the deploy user. Your suggestion to use `bash -c "..."` as ssh command (and pass all remote commands to it) would work, but would require to change all quoting of [existing code snippets](https://github.com/boldpoker/edeliver/blob/f62cfbd4e6c83614636f2659cb5c299a75e31e49/libexec/erlang#L117) to less readable, harder to write and more error-prone [double quoting](https://github.com/boldpoker/edeliver/blob/f62cfbd4e6c83614636f2659cb5c299a75e31e49/libexec/erlang#L722). Maybe supporting another shell would be also an option (if it is a common one) and maybe it would not even require to change that many lines of code. Can you check which shell is the default one on your system?

**Comment by kuon** [comment]
`sh` is the default on FreeBSD for new users.

I think it's not an issue as long it is documented. Just add a line like "bash should be the shell of the ssh user". Also, perhaps add a check for bash as first thing?

**Comment by kuon** [comment]
To check the current shell `echo $0` should work with `bash` and `zsh`, it can be prefixed by `-` for login shell. Also checking `$BASH_VERSION`.

**Comment by bharendt** [comment]
Replaced this issue with #143.
