### ISSUE TITLE
Adding distillery support ?

### ISSUE THREAD

**Issue by pikeas** [boldpoker/edeliver#128]
http://bitwalker.org/posts/2016-07-21-distillery-vs-exrm-vs-relx/

> Ultimately, I would see Distillery replacing Exrm in edeliver, but currently that is not the case. As far as I’m aware, the comparison of these three tools does not impact edeliver to any significant degree, as it just needs a tool to package a release, and takes it from there. If anyone from the edeliver team reads this, and would like to connect on how to make the most use of Distillery, I’d be glad to do so!

**Comment by bharendt** [comment]
I think we should add support for it very soon. Thanks for the hint.

**Comment by bharendt** [comment]
[Distillery](https://github.com/bitwalker/distillery) support is included in the [hex release `1.3.0`](https://hex.pm/packages/edeliver/1.3.0). Test-releases built very fast and without difficulties. Thanks for all the good work @bitwalker !

**Comment by bitwalker** [comment]
Hey this is great news! I was thinking about dropping by soon to suggest this, but it looks like you guys are right on top of it :). Let me know if you run into any issues, or have feedback I can use to improve Distillery!

**Comment by bharendt** [comment]
@bitwalker Looks good so far! We're just discussing to release edeliver 2.0 alongside Distillery 1.0, see https://github.com/boldpoker/edeliver/milestone/1

We're also thinking of starting a elixir-deployment mailing list and move support requests there. Would you be interested in joining there?

**Comment by bharendt** [comment]
Added a basic [wiki page](https://github.com/boldpoker/edeliver/wiki/Upgrade-from-exrm-to-distillery-as-build-tool) how to upgrade from exrm to distillery. Please feel free to improve it.

**Comment by bitwalker** [comment]
@bharendt Sure, I'd be glad to join the mailing list, a unified list for all projects like ours would be great! I wonder if it might not be worth discussing with the folks over at Elixir Forum to get a dedicated forum for deployment rather than start a new mailing list, in the interest of making it more accessible. That said, either way I'm in!

**Comment by mk** [comment]
@bitwalker Elixir Forum on deployment sounds even better, I'll get in touch with them, thanks!
