### ISSUE TITLE
Starting App after Reboot

### ISSUE THREAD

**Issue by samhamilton** [boldpoker/edeliver#130]
Thanks for the great software, I got my servers running in no time and sorry if this is answered elsewhere; how do I get my last deployed and running app to start after the server is rebooted to start automatically, say after a kernel upgrade? 

Thanks
Sam

**Comment by bharendt** [comment]
To automatically start your erlang / elixir application after a reboot you would need to create a linux init script which calls `/<path-to-your-release>/$APP/bin/$APP start`. The contents of the init script depends on the linix distribution you are using and edeliver does not provide any. 

To start your application after a reboot on the deploy hosts manually, you can use the following edeliver command:

```
mix edeliver start [staging|production] 
```

If you have several deploy hosts and only one is restarted, you can use the `--host=[u@]<your-single-host.net>` option to start only that single one.

**Comment by hamann** [comment]
Here's an example init script for upstart systems https://github.com/boldpoker/edeliver/wiki/Example-Init-Scripts

**Comment by samhamilton** [comment]
Many thanks!
