### ISSUE TITLE
Is there a way to access global environment variables?

### ISSUE THREAD

**Issue by austinsmorris** [boldpoker/edeliver#136]
Basically, I want to set `BUILD_USER=USER` where `USER` is the current environment user (me).  Is it possible to access all the environment variables from `printenv` when using edeliver?

**Comment by bharendt** [comment]
You can set `BUILD_USER="$USER"` in your edeliver config. You can also use any other environment variable available at your local development machine. But the user must then also exists on the build host.

**Comment by austinsmorris** [comment]
Awesome, thanks!
