### ISSUE TITLE
Wrongly detected branch

### ISSUE THREAD

**Issue by gaynetdinov** [boldpoker/edeliver#137]
Hello. 

I've noticed that `branch` is not always detected correctly. 

```sh
damir:my_service/ (elixir-1-3) $ mix edeliver version qa1                                                              

EDELIVER MY_SERVICE WITH VERSION COMMAND

-----> getting release versions from qa1 servers

qa1 node:

  user    : myuser
  host    : myhost.com
  path    : /home/user/my_service/
  response: 0.0.1+master-bcf0706-qa
  branch  : elixir-1-3
  date    : 2016-07-22 10:30:17 +0200 (git commit)
  commits : Merge pull request #32 from adjust/decrease-connection-pool-for-qa-and-demo
            Decrease number of db connections for qa and demo
            Fix test env after adding airbax
            Merge pull request #31 from adjust/airbax
            Airbrakex -> Airbax
            ...

VERSION DONE!        
```

As you can see, `branch` in the output is shown as my local branch(elixir-1-3) instead of deployed branch(which is `master`, you can see it from `response` field, because I have branch name in `AUTO_VERSIONING`).

**Comment by bharendt** [comment]
Does the commit maybe exist in different branches, e.g a feature branch and was later merged into master? edeliver tries to detect the branch which contains the commit by using the [following command](https://github.com/boldpoker/edeliver/blob/616c04de492bf3813568e3069a709995287d8884/strategies/erlang-node-execute#L177): `git branch -a --contains "$_revision"` and returns only the first match.
