### ISSUE TITLE
Failure during "Stashing build directory"

### ISSUE THREAD

**Issue by antipax** [boldpoker/edeliver#14]
Hi, I just added edeliver to my project and I'm getting this error:
```
BUILDING RELEASE OF PRIVATE APP ON BUILD HOST

-----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
-----> Pushing new commits with git to: root@private
Everything up-to-date
-----> Resetting remote hosts to 81f27e2556d3e62ae0cbf4bd2ab016311b7cc44c
HEAD is now at 81f27e2 update comeonin
-----> Stashing build directory on remote build host

FAILED  1:
ssh -o ConnectTimeout=3 root@private
    set -e
    [ -f ~/.profile ] && source ~/.profile
    cd /opt/private/builds 
    [[ $(git stash list | wc -l) -gt 0 ]] && _oldest_stash=$(git stash list | tail -1 | grep -o 'stash@{[0-9]\+}' | grep -o '[0-9]\+') || _oldest_stash=0
    [[ ${_oldest_stash} -gt 50 ]] && git stash drop stash@{$_oldest_stash} 
    git stash --all 
```
Any idea what could be going wrong here? If I paste that command into the terminal it completes successfully.

Also, it appears that neither --verbose or -V have any effect.

**Comment by antipax** [comment]
Sorry, accidentally submitted, issue content coming in a second

**Comment by bharendt** [comment]
My first idea was, that it might be an issue with the __version of git__ that is installed on the build hosts, or that git aborts because it wants you to __set__ some initial data, like the __git user name or email__.

But if the commands execute in the terminal, they should also run from the edeliver script.
Maybe it helps to figure out which of the commands fail, if you add some debug output to
[git_stash_remote() in libexec/erlang](https://github.com/boldpoker/edeliver/blob/master/libexec/erlang#L764-L774), e.g. like that:

	diff --git a/libexec/erlang b/libexec/erlang
	index 75d38f2..07897bd 100644
	--- a/libexec/erlang
	+++ b/libexec/erlang
	@@ -767,9 +767,11 @@ git_stash_remote() {
	     set -e
	     [ -f ~/.profile ] && source ~/.profile
	     cd $DELIVER_TO $SILENCE || echo 'DELIVER_TO path does not exist'
	+    git stash list || echo 'git stash list failed' 
	+    wc | echo 'wc missing'
	     [[ \$(git stash list | wc -l) -gt 0 ]] && _oldest_stash=\$(git stash list | tail -1 | grep -o 'stash@{[0-9]\+}' | grep -o '[0-9]\+') || _oldest_stash=0
	+    [[ \${_oldest_stash} -gt 50 ]] && echo \"trying to drop older stash stash@{\$_oldest_stash}\"
	     [[ \${_oldest_stash} -gt 50 ]] && git stash drop stash@{\$_oldest_stash} $SILENCE
	-    git stash --all $SILENCE
	+    git stash --all $SILENCE || echo 'actual stashing failed'
	   "
	 }

`--verbose or -V` doesn't have any effect in that case, because all commands except the `git stash --all`  have no output.

**Comment by antipax** [comment]
Ok, thanks very much for your help so far and I will get back to you with my findings

**Comment by bharendt** [comment]
Or maybe the git commmands don't work with the __build user__, but you tried with a different user in the terminal

**Comment by antipax** [comment]
Nope, it was root both times

**Comment by antipax** [comment]
Tried your patch, didn't produce any new output:

```
FAILED  1:
ssh -o ConnectTimeout=3 root@private
    set -e
    [ -f ~/.profile ] && source ~/.profile
    cd /opt/turbo/builds 
    git stash list || echo 'git stash list failed'
    [[ $(git stash list | wc -l) -gt 0 ]] && _oldest_stash=$(git stash list | tail -1 | grep -o 'stash@{[0-9]\+}' | grep -o '[0-9]\+') || _oldest_stash=0
    [[ ${_oldest_stash} -gt 50 ]] && echo "trying to drop older stash stash@{$_oldest_stash}"
    [[ ${_oldest_stash} -gt 50 ]] && git stash drop stash@{$_oldest_stash} 
    git stash --all  || echo 'actual stashing failed'
```

Also tried those commands bare in the terminal after logging into the server with the given ssh invocation, no new output

```
╰─$ ssh root@private-base                                                                                                                                                                                                         1 ↵
Welcome to Ubuntu 12.04.5 LTS (GNU/Linux 3.2.0-80-virtual x86_64)

0 packages can be updated.
0 updates are security updates.



*** /dev/xvda1 will be checked for errors at next reboot ***

*** System restart required ***

This server is in Puppet environment 'private'.
Carry on...
Last login: Tue May 26 07:58:54 2015 from 172.31.1.10
root@private-base:~#     set -e
root@private-base:~#     [ -f ~/.profile ] && source ~/.profile
root@private-base:~#     cd /opt/private/builds 
root@private-base:/opt/private/builds#     git stash list || echo 'git stash list failed'
root@private-base:/opt/private/builds#     [[ $(git stash list | wc -l) -gt 0 ]] && _oldest_stash=$(git stash list | tail -1 | grep -o 'stash@{[0-9]\+}' | grep -o '[0-9]\+') || _oldest_stash=0
root@private-base:/opt/private/builds#     [[ ${_oldest_stash} -gt 50 ]] && echo "trying to drop older stash stash@{$_oldest_stash}"
root@private-base:/opt/private/builds#     [[ ${_oldest_stash} -gt 50 ]] && git stash drop stash@{$_oldest_stash} 
root@private-base:/opt/private/builds#     git stash --all  || echo 'actual stashing failed'
No local changes to save
```

any other ideas?

**Comment by bharendt** [comment]
Hmm, does `root@private` and `root@private-base` login to the same host?

**Comment by antipax** [comment]
Yes, sorry, I just manually replaced a product name. They are both definitely connecting to the same host

**Comment by bharendt** [comment]
ah, ok

**Comment by bharendt** [comment]
Maybe you can try again and uncomment the lines that drop older stashes:

		 set -e
	     [ -f ~/.profile ] && source ~/.profile
	     echo 'changing to build directory'
	     cd $DELIVER_TO $SILENCE 
	     #[[ \$(git stash list | wc -l) -gt 0 ]] && _oldest_stash=\$(git stash list | tail -1 | grep -o 'stash@{[0-9]\+}' | grep -o '[0-9]\+') || _oldest_stash=0
	     #[[ \${_oldest_stash} -gt 50 ]] && echo \"trying to drop older stash stash@{\$_oldest_stash}\"
	     #[[ \${_oldest_stash} -gt 50 ]] && git stash drop stash@{\$_oldest_stash} $SILENCE
	     echo 'stashing build directory' 
	     git stash --all && echo 'stashing succeeded' || echo 'stashing failed' 
	   "

Or remove the `set -e` instruction temporarily. It is used to abort everything if a single command fails.

**Comment by bharendt** [comment]
But i don't have a good explanation why it doesn't work in the script, if it works in the console. Maybe your ssh is configured to export some different environment, e.g. `GIT_EDITOR` or something, which is then missing on the build hosts.

**Comment by antipax** [comment]
Ok, thanks, that put me in the right direction. Removing set -e made it work, and I was able to reduce the error producing case to this:

```
FAILED  1:
ssh -o ConnectTimeout=3 root@turbo-base.east.fdbox.net 
    set -e
    [ -f ~/.profile ] && source ~/.profile
```

I think I know what is happening now, finally... my /root/profile does not return 0 on when the terminal is not a tty, due to an old ubuntu bug. By making sure it returned 0 in all cases, sourcing the profile no longer caused an abort due to `set -e`.

**Comment by antipax** [comment]
Thanks for your help with this, definitely wasn't an issue with edeliver at all, but hopefully if someone runs into the same issues as I did they will see this and it will help. Closing this now

**Comment by bharendt** [comment]
True, quite tricky error, but think that might easily happen also to others. Think it will make sense to move the `set -e` instruction below the `[ -f ~/.profile ] && source ~/.profile` wherever it is used.

**Comment by antipax** [comment]
Yeah, that makes sense to me. Also, is it necessary to even source the user's profile? Shouldn't that already be sourced by the shell no matter what?

**Comment by bharendt** [comment]
This is taken from [deliver](https://github.com/gerhard/deliver). I think ssh reads the `~/.profile` ony if a pseudo-tty is allocated.

**Comment by antipax** [comment]
Ah, ok. Makes sense
