### ISSUE TITLE
Install distillery from github fails

### ISSUE THREAD

**Issue by schurig** [boldpoker/edeliver#149]
### Environment

* Edeliver version (`mix edeliver --version`): 1.4.0
* Elixir version (`elixir -v`): 1.3.2
* Build tool and version (distillery|exrm): distillery (master branch from github)
* Operating system (on build / deploy hosts): ubuntu
* Are you using an umbrella project (yes|no): no

### Verbose output

```
Dependencies have diverged:
* distillery (https://github.com/bitwalker/distillery.git)
  the dependency distillery in mix.exs is overriding a child dependency:

  > In mix.exs:
    {:distillery, [env: :prod, git: "https://github.com/bitwalker/distillery.git", overwrite: true, warn_missing: false, manager: :mix]}

  > In deps/edeliver/mix.exs:
    {:distillery, ">= 0.8.0", [env: :prod, hex: :distillery, optional: true]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies
```

### Current behavior

when using `{:distillery, git: "https://github.com/bitwalker/distillery.git", warn_missing: false}` and  executing`mix deps.get` it fails with the error above. I want to test the latest commits of distillery.

### Expected behavior

Github branch should work fine.

**Comment by bitwalker** [comment]
You should be able to pass `override true` to the dependency in your mix.exs to fix this, e.g:

```elixir
{:distillery, github: "bitwalker/distillery", [warn_missing: false, override: true]}
```

**Comment by schurig** [comment]
Ahh thanks!!

```elixir
{:distillery, [github: "bitwalker/distillery", warn_missing: false, override: true]}
```
worked for me
