### ISSUE TITLE
Deploy and run multiple environments on one host

### ISSUE THREAD

**Issue by jaminthorns** [boldpoker/edeliver#158]
Hello,

I've been trying to configure edeliver to deploy and run multiple environments on a single host/machine, with no luck so far. I'm able to deploy to 2 separate locations on the same host, and I can start up 1 environment, but then if I try to start up the other, it detects that the first instance is already running and won't let me start the second. I tried creating different users for the 2 difference environments, but that made no difference.

I know this isn't best practice by any standards, but I was just wondering if it is at all possible. Thanks!

**Comment by bharendt** [comment]
Hello,

If you need to run two different environments on the same host, you need two different deploy destinations `DELIVER_TO` for the production release and `TEST_AT` for the staging release. It is also recommended to use different users then for the different environments (`PRODUCTION_USER` and `STAGING_USER`) and that's what you did already. What you are still missing is: to use different configurations for your environment. So you could use `LINK_SYS_CONFIG` and e.g. set it to `~/my-app.config` and especially `LINK_VM_ARGS` and e.g. set it to `~/vm.args`. You have to use __different node names__ in the `vm.args` if you want to run several instances on the same host. e.g. you could keep the default node name in `/home/<production-user>/vm.args` and use a different one in `/home/<staging-user>/vm.args` by changing the `-name` option e.g. to `-name staging-server@127.0.0.1`.

**Comment by jaminthorns** [comment]
Thanks so much!

**Comment by christopheradams** [comment]
@bharendt can you provide more details about how this is supposed to work?

```bash
# .deliver/config
LINK_VM_ARGS=~/vm.args
```

When I deploy the release to my server, the `vm.args` file is symlinked to a file *my* home directory, which of course does not exist on the server. I'm using Distillery with `plugin Releases.Plugin.LinkConfig`. (after #174)

See also #155 where the same solution is proposed.

**Comment by christopheradams** [comment]
For what it's worth, I had better luck with relative links. Something like:

```
LINK_VM_ARGS="../../../../vm.args"
```

**Comment by bharendt** [comment]
Thanks @christopheradams. You are right: linking to the home directory `~` is expanded to the current home on the build host and not to the "relative" home directory of the current user on the staging / production host(s). `~` is actually an alias to the fixed path of the current home directory, not a relative path. So linking the config to a file in `~` does not work and your solution with the relative path is maybe a good workaround, if there should run several instances on the same host with different configurations. Will add that to the [wiki page](https://github.com/boldpoker/edeliver/wiki/Use-per-host-configuration). Another option might be to set the [`ERL_FLAGS`](http://erlang.org/doc/man/erl.html#ERL_FLAGS) env in the users `~/.profile` and override either the config file to use by setting the `-config $HOME/my.sys.config` option or override / set single application options using the `-Application Par Val` option.
