### ISSUE TITLE
generating release get warning release.init task first

### ISSUE THREAD

**Issue by michelson** [boldpoker/edeliver#161]
### Precheck

I'm trying to use distillery (after use exrm) with edeliver, when is Generating release somehow it don't generate release file, so it fails. (error below)
But If I enter the server and go to build path I can successfully run ` mix release.init task first` and then the ```MIX_ENV="prod" LINK_SYS_CONFIG="" LINK_VM_ARGS="" APP="vadb_events" AUTO_VERSION="commit-count+git-revision+branch-unless-master" BRANCH="master" SKIP_RELUP_MODIFICATIONS="" RELUP_MODIFICATION_MODULE="" USING_DISTILLERY="true" mix do release.version ,  release --verbose --env="prod" --name="vadb_events"``` to generate the release, then it works.

### Environment
* config: 
     + AUTO_VERSION=commit-count+git-revision+branch-unless-master
     + USING_DISTILLERY=true```
* Edeliver version (`mix edeliver --version`): edeliver v1.4.0
* Elixir version (`elixir -v`): 1.3.3
* Build tool and version (distillery|exrm): distilery
* Operating system (on build / deploy hosts): ubuntu
* Are you using an umbrella project (yes|no): no

### Verbose output

```
...
-----> Generating release
stdin: is not a tty
using mix to generate release
==> Loading configuration..
==> You are missing a release config file. Run the release.init task first

A remote command failed on:

  root@my.ip

Output of the command is shown above and the command executed
on that host is printed below for debugging purposes:

FAILED with exit status 1:

    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd /tmp/edeliver/events/builds
    if [ "mix" = "rebar" ]; then
      echo "using rebar to generate release"
      ./rebar   -f generate
    elif [ "mix" = "relx" ]; then
      echo "using relx to generate release"
      ./relx release
    elif [ "mix" = "mix" ]; then
      echo "using mix to generate release"
      MIX_ENV="prod" LINK_SYS_CONFIG="" LINK_VM_ARGS="" APP="vadb_events" AUTO_VERSION="commit-count+git-revision+branch-unless-master" BRANCH="master" SKIP_RELUP_MODIFICATIONS="" RELUP_MODIFICATION_MODULE="" USING_DISTILLERY="true" mix do release.version ,  release --verbose --env="prod" --name="vadb_events"
    fi

```

**Comment by bharendt** [comment]
You have to run the `mix release.init` task once locally, maybe modify the generated config file from `rel/config.exs` and then add this file to your repository to be able to build distillery releases on the build host.

**Comment by michelson** [comment]
thanks @bharendt , it works 👌
