### ISSUE TITLE
Use edeliver features in an umbrella app

### ISSUE THREAD

**Issue by philipgiuliani** [boldpoker/edeliver#162]
### Environment
- Edeliver version: 1.4.0
- Elixir version: 1.3.3 (OTP 19)
- Build tool and version: distillery
- Operating system: Ubuntu 16.04 (build + production)
- Are you using an umbrella project: yes
### Current behaviour

The commands which require edeliver to be defined as application do not work:
- mix edeliver version production
- mix edeliver show migrations on production
- mix edeliver migrate production

They all fail with the following error:

```
server (master) $ mix edeliver show migrations production --verbose

EDELIVER MYAPP WITH MIGRATIONS COMMAND

-----> migrationsing production servers

production node:

  user    : server
  host    : THE_IP
  path    : /home/server/app
  response: RPC to 'app@127.0.0.1' failed: {'EXIT',
                                  {{badmatch,nil},
                                   [{'Elixir.Edeliver',run_command,1,
                                     [{file,"lib/edeliver.ex"},{line,63}]},
                                    {rpc,'-handle_call_call/6-fun-0-',5,
                                     [{file,"rpc.erl"},{line,187}]}]}}

MIGRATIONS DONE!
```
### Release configuration

I have tried both ways to release the application:

```
#1.
release :app do
  set version: current_version(:api)
end

#2.
release :app do
  set version: "0.1.0"
  set applications: [:api]
end
```

The application i want to deploy is `api` which is a Phoenix App that depends on other applications.

I also tried to add edeliver as dependency + application to the `api` project, just to get this features working.
### Expected behavior

I would expect to have it working like when im not deploying umbrella applications

**Comment by st23am** [comment]
I am experiencing the same thing.

**Comment by lessless** [comment]
Confirming

**Comment by willwatson27** [comment]
ditto

**Comment by sabondano** [comment]
Did any of you figure this out? or make any progress with this?

**Comment by philipgiuliani** [comment]
@sabondano No. I tried out some ways which could have worked, but no luck for me :( What i currently do, is going in the build folder and running `mix ecto.migrate` after every deployment which has migrations. Not the best way, but i'm not in production yet :)

**Comment by BartOtten** [comment]
Having the same issue :-(

**Comment by philipgiuliani** [comment]
@bharendt Just want to be sure that you are aware of this issue :) Would be nice to get this working :) Or at least a workaround?

**Comment by bharendt** [comment]
Is your app included in the list of running applications which is returned by [`:application.which_applications`](https://github.com/boldpoker/edeliver/blob/v1.4.0/lib/edeliver.ex#L63) when you connect to the node using the `remote_console`?
If yes, you could check whether [`APP=api`](https://github.com/boldpoker/edeliver/blob/v1.4.0/lib/edeliver.ex#L44) is set in `.deliver/config` correctly, if not you could try to add your application explicitly to the `application` section in your mix file, e.g like that:
```elixir
defmodule Api.Mixfile do
  use Mix.Project

  def project do
    # [...]
  end

  def application do
    [mod: {Api, []},
     applications: [
      # ... dependencies
      :api
     ]
    ]
  end
#...
```

**Comment by BartOtten** [comment]
1. No
2. Tried it. Didn't work for me :'(

**Comment by philipgiuliani** [comment]
Thanks for the answer!

In an Umbrella if you run `mix ecto.migrate` it runs the migrations for all apps, and that is also what I would expect from edeliver. I have migrations in 3 apps (base, chat, auth), and not in API.

**Comment by archSeer** [comment]
I asked the same question on #elixir-lang today, edeliver needs to be added to the applications list, but that can't be done in the umbrella root. If you're using distillery however, you can specify it to be appended inside `rel/config.exs`:

```
release :myapp do
  set version: current_version(:myapp)
  set applications: [:myapp, :edeliver]
end
```

**Comment by brettv** [comment]
No luck on my end with the suggestion from @archSeerno.  

I seem to get the same error without or without adding edeliver to the distillery config.  

When I specify the ECTO_REPOSITORY I see this:                                

```
{'EXIT',
  {undef,
   [{'Properties.Repo','__adapter__',[],[]},
    {'Elixir.Ecto.Migration.SchemaMigration',
     'ensure_schema_migrations_table!',2,[]},
    {'Elixir.Ecto.Migrator',
     migrated_versions,2,
     [{file,"lib/ecto/migrator.ex"},
      {line,43}]},
    {'Elixir.Ecto.Migrator',run,4,
     [{file,"lib/ecto/migrator.ex"},
      {line,142}]},
    {rpc,'-handle_call_call/6-fun-0-',5,
     [{file,"rpc.erl"},{line,187}]}]}}
```

When I don't, I see this:

```
{'EXIT',
  {{case_clause,{ok,[]}},
  [{'Elixir.Edeliver','ecto_repository!',2,
    [{file,"lib/edeliver.ex"},{line,154}]},
   {'Elixir.Edeliver',migrate,5,
    [{file,"lib/edeliver.ex"},{line,127}]},
   {rpc,'-handle_call_call/6-fun-0-',5,
    [{file,"rpc.erl"},{line,187}]}]}}
```

**Comment by archSeer** [comment]
That looks like a different error. The original in this issue is
```
{'EXIT',
                                  {{badmatch,nil},
                                   [{'Elixir.Edeliver',run_command,1,
                                     [{file,"lib/edeliver.ex"},{line,63}]},
                                    {rpc,'-handle_call_call/6-fun-0-',5,
                                     [{file,"rpc.erl"},{line,187}]}]}}
```

Which fails because edeliver is not loaded in the umbrella app, so version/migrations don't function. Adding :edeliver to the rel/config fixes that, seems to work fine for us.

Your failure seems to be specific to the ecto repository, after specifying ECTO_REPOSITORY it seems to fail with no adapter I guess. Maybe make sure you're including all your dependencies inside the applications struct? [Distillery will explicitly warn you about that on a local build](https://hexdocs.pm/distillery/cli.html#missing-applications) (`MIX_ENV=prod mix release --env=prod`).

**Comment by philipgiuliani** [comment]
It worked for me @archSeer ! :)

@bharendt What do you think about adding this information in the README?

```
release :myapp do
  set version: "0.0.1"
  set applications: [:api, :admin, :edeliver]
end
```

**Comment by brettv** [comment]
thanks @archSeer.  I will check that out.

**Comment by benrom** [comment]
This didn't work for me even though :edeliver is added to the distillery config release.
It fails with the same RPC error as @philipgiuliani for both `mix edeliver show migrations` and `mix edeliver versions`.

I can see both my umbrella app and edeliver within `:application.which_applications`.

**Comment by novaugust** [comment]
Seems to me it's rooted in what @BartOtten said. The umbrella APP is not actually an app that gets bundled up with the release, per that conversation, so `which_applications` returns nil and nothing goes through. This would work if we could specify which app we're attempting to migrate without changing the name of the executable

**Comment by brettv** [comment]
I found the root of my issue incase anyone cases.  Basically, in my umbrella app, the "main" app (the one that the config script points to) doesn't contain the repo.  So when this line:

https://github.com/boldpoker/edeliver/blob/master/lib/edeliver.ex#L127

computes the directory that contains all the migrations, it assumes the migrations are located in the priv folder of the main app.

My options seem limited.  I could fork this and have it working in minutes, but I hesitate because it would likely not have much value to the community at large since it would have to make assumptions (based on the Repo module name most likely) to find the directory with the migrations.

Or I could hack it through a config script hook (somewhere around `erlang_generate_release` or `erlang_archive_release`) and have it copy the `priv/repo/migrations` from the sub-app to the main app to trick it into thinking it has all the migrations.

Any ideas?  Officially supported options I didn't see?

**Comment by novaugust** [comment]
@brettv we ended up forking (boldpoker doesn't seem to be actively maintaining) and adding a configuration value `REPO_APP`
https://github.com/Enbala/edeliver/commit/6219da9721e304a5ccc3afa4278d29ef729be84b
The code was meant to continue working the way it currently does if `REPO_APP` isn't defined, but looking at what I wrote, it doesn't look like that's the case...

anyways, we just added a `REPO_APP=OurRepoApp` to the .deliver/config and voila

**Comment by brettv** [comment]
Thanks @novaugust!  That worked!  

For anyone else following this, make sure you use the branch named set_repo_app on the Enbala fork.

**Comment by odarriba** [comment]
What about having that patch merged in edeliver? @benrom

**Comment by benrom** [comment]
@odarriba it would be nice yes!

**Comment by zimt28** [comment]
Does anyone know a working solution for current versions of Phoenix/ Edeliver and Distillery?

**Comment by sircharleswatson** [comment]
I'm still running into this issue. I can't migrate my umbrella app even with `:edeliver` added to `rel/config.exs`

**Comment by Preen** [comment]
+1 @sircharleswatson and the fork @novaugust and @brettv is 404.

**Comment by novaugust** [comment]
See #235 for latest

**Comment by jrissler** [comment]
Added @archSeer 's solution to app and deployed, was def not migrated. However, where this was previously failing "mix edeliver migrate production --verbose" - it now works + migrated database. This is obviously not ideal - but IT WORKS :)

**Comment by lessless** [comment]
Hello folks, 

For anyone experiencing problem with picking up migrations from applications other than main app - the discussion will continue in https://github.com/edeliver/edeliver/issues/235
