### ISSUE TITLE
compile fails with Elixir v 1.3.0 & 1.3.2

### ISSUE THREAD

**Issue by netflakes** [boldpoker/edeliver#163]
### Environment

* Edeliver version (`mix edeliver --version`):
* Elixir version: 1.3.0  & 1.3.2
* Build tool and version (distillery|exrm): BOTH
* Operating system (on build / deploy hosts): Ubuntu
* Are you using an umbrella project (yes|no): NO

###Command that fails

** (Mix) Cannot execute task because the project was not yet compiled. When build_embedded is set to true, "MIX_ENV=prod mix compile" must be explicitly executed

### Code that fails is in libexec/erlang

```    elif [ \"$BUILD_CMD\" = \"mix\" ] && [ \"$RELEASE_CMD\" = \"mix\" ]; then
      echo \"Checking whether deps must be compiled for mix version 1.3.0\"
      # see https://github.com/boldpoker/edeliver/issues/94
      if $MIX_CMD --version | grep 'Mix 1.3.0' >/dev/null 2>&1 ; then
        echo \"Compiling deps because mix version 1.3.0 is used\"
        APP=\"$APP\" MIX_ENV=\"$TARGET_MIX_ENV\" $MIX_CMD deps.compile
      fi
```

### Comments:

Initially I thought the issue was only with 1.3.2 - I then downgraded to 1.3.0 and experience the same issue. I haven't tried to downgrade to 1.2.5 as I have to make some code changes for that.. Ideally I would love this to work with 1.3.2.

Any thoughts?

### Verbose output

EDELIVER SCOUT_RESUME_API WITH UPDATE COMMAND

-----> Updating to revision 2375baf from branch master
-----> Building the release for the update
-----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
-----> Pushing new commits with git to: scout@ec2-54-206-31-148.ap-southeast-2.compute.amazonaws.com
-----> Resetting remote hosts to 2375baffed7ba4ac9c802a3ab46f039af4bb27d2
-----> Cleaning generated files from last build
-----> Fetching / Updating dependencies
-----> Preparing assets with: brunch build and phoenix.digest
-----> Compiling sources
Checking whether deps must be compiled for mix version 1.3.0
Compiling deps because mix version 1.3.0 is used
==> poolboy (compile)
===> Compiling getopt
===> Compiling providers
===> Compiling cf
==> erlware_commons (compile)
==> ranch (compile)
==> eporter (compile)
===> Compiling bbmustache
===> Compiling relx
==> cowlib (compile)
==> cowboy (compile)
Compiled src/cowboy_protocol.erl
==> tirexs
warning: the dependency :tirexs requires Elixir "~> 1.2.0" but you are running on v1.3.0
==> ibrowse (compile)
** (Mix) Cannot execute task because the project was not yet compiled. When build_embedded is set to true, "MIX_ENV=prod mix compile" must be explicitly executed

A remote command failed on:

  scout@ec2-54-206-31-148.ap-southeast-2.compute.amazonaws.com

Output of the command is shown above and the command executed
on that host is printed below for debugging purposes:

FAILED with exit status 1:

    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd /tmp/edeliver/scout_resume_api/builds
    if [ "mix" = "rebar" ]; then
      echo "using rebar to compile files"
      [[ "" != "true" ]] && ./rebar  clean skip_deps=true || :
      ./rebar  compile
    elif [ "mix" = "mix" ] && [ "mix" = "mix" ]; then
      echo "Checking whether deps must be compiled for mix version 1.3.0"
      # see https://github.com/boldpoker/edeliver/issues/94
      if mix --version | grep 'Mix 1.3.0' >/dev/null 2>&1 ; then
        echo "Compiling deps because mix version 1.3.0 is used"
        APP="scout_resume_api" MIX_ENV="prod" mix deps.compile
      fi
      if [[ "" = "true" ]]; then
        APP="scout_resume_api" MIX_ENV="prod" AUTO_VERSION="commit-count+branch+git-revision" SKIP_RELUP_MODIFICATIONS="" RELUP_MODIFICATION_MODULE="" mix do release.version  , compile
      else
        APP="scout_resume_api" MIX_ENV="prod" AUTO_VERSION="commit-count+branch+git-revision" SKIP_RELUP_MODIFICATIONS="" RELUP_MODIFICATION_MODULE="" mix do clean, release.version  , compile
      fi
    elif [ "mix" = "mix" ]; then
      echo "using mix to compile files"
      if [[ "" = "true" ]]; then
        if [[ -n "commit-count+branch+git-revision" ]]; then
          hint_message 'Using --auto-version together with --skip-mix-clean would not work!'
        fi
        APP="scout_resume_api" MIX_ENV="prod" AUTO_VERSION="commit-count+branch+git-revision" BRANCH="master" SKIP_RELUP_MODIFICATIONS="" RELUP_MODIFICATION_MODULE="" mix do deps.compile, release.version  , compile
      else
        APP="scout_resume_api" MIX_ENV="prod" AUTO_VERSION="commit-count+branch+git-revision" BRANCH="master" SKIP_RELUP_MODIFICATIONS="" RELUP_MODIFICATION_MODULE="" mix do clean, deps.compile, release.version  , compile
      fi
    fi

**Comment by bharendt** [comment]
Can you tell which dependency cannot be compiled? Is it the `ibrowse` dependency or that one that would have been compiled as next dependency? You can check that by cleaning the build output of the deps using `mix deps.clean --build --all` and then run `mix.deps compile` manually
and check the beam file output in `_build/<env>/lib/<dep>/ebin/*.beam`.

**Comment by philipgiuliani** [comment]
Hi! I had the same issue.
It is a bug in elixir which should be fixed in the next bugfix release.
See: https://github.com/elixir-lang/elixir/issues/5094

I am currently using a fork that did a workaround for the bug:
```
{:edeliver, github: "schnittchen/edeliver"}
```

**Comment by netflakes** [comment]
Thanks - I tried that fork as well - and it at least gave me more "feedback" and yes it errors when trying to compile 'ibrowse'...

**Comment by netflakes** [comment]
Turns out "tirexs" was the issue - now that I have refactored the module that was using it to work with the latest changes - I can deploy with the "schnittchen" fork 👍  - THANKS

**Comment by dfcarpenter** [comment]
@netflakes Could you elaborate what was wrong with tirexs that was causing the issue?
