### ISSUE TITLE
mix edeliver build release fails to find built release

### ISSUE THREAD

**Issue by romul** [boldpoker/edeliver#17]
```
$ mix edeliver build release --verbose
...
==> Building release with MIX_ENV=prod.
==> Generating relx configuration...
==> Generating sys.config...
==> Generating boot script...
==> Performing protocol consolidation...
==> Conform: Loading schema...
==> Conform: No schema found, conform will not be packaged in this release!
==> Generating release...
==> Generating nodetool...
==> Packaging release...
==> The release for myapp-0.0.1 is ready!
-----> Copying release to local release store
-----> Copying myapp-0.0.1.tar.gz to release store
scp: /tmp/erlang/myapp/builds/rel/myapp/myapp-0.0.1.tar.gz: No such file or directory

RELEASE BUILD OF MYAPP WAS SUCCESSFUL!
```
But there is a file ` /tmp/erlang/myapp/builds/rel/myapp/releases/0.0.1/myapp.tar.gz`

```
$ ls /tmp/erlang/myapp/builds/rel/myapp/releases/0.0.1/
итого 20660
drwxrwxr-x 2 deployer deployer     4096 Июл 10 11:34 ./
drwxrwxr-x 3 deployer deployer     4096 Июл 10 11:34 ../
-rw-rw-r-- 1 deployer deployer    37894 Июл 10 11:34 myapp.boot
-rw-rw-r-- 1 deployer deployer      548 Июл 10 11:34 myapp.rel
-rw-rw-r-- 1 deployer deployer    51350 Июл 10 11:34 myapp.script
-rw-rw-r-- 1 deployer deployer 20997987 Июл 10 11:34 myapp.tar.gz
-rw-rw-r-- 1 deployer deployer    37894 Июл 10 11:34 start.boot
-rw-rw-r-- 1 deployer deployer      912 Июл 10 11:34 sys.config
-rw-rw-r-- 1 deployer deployer      421 Июл 10 11:34 vm.args
```

And `mix edeliver deploy release` fails too:
```
$ mix edeliver deploy release to staging
DEPLOYING RELEASE OF MYAPP APP TO STAGING HOSTS

-----> Authorizing hosts
ls: .deliver/releases/myapp_*.*.tar.gz: No such file or directory
No *(s) found in local release store.
You can build one with the ./edeliver build * task.
```

Any insights how to build proper release?

**Comment by romul** [comment]
I figured out a source of that issue. It's because of this commit: https://github.com/bitwalker/exrm/commit/4b7d9f2118b446b938a1ca7449c9c3a5d0566556

**Comment by bitwalker** [comment]
@romul pointed me to this project, and I'd like to help get things working again, though I'd like to prevent copying the generated tarballs if possible. Is there a place I can get started looking to implement a fix for this? Basically we just need to get the release tarball from `rel/app/app-<version>.tar.gz` or, if it doesn't exist, get it from `rel/app/releases/<version>/app.tar.gz`, otherwise fail.

**Comment by bharendt** [comment]
@romul thanks for posting this and already providing the reason / solution. and
@bitwalker, thanks for providing help. 
I added this [commit](https://github.com/boldpoker/edeliver/commit/030dca78c17da85022483c1f988c8f039cc71633) and use the new location of the generated tar if the exrm version is >= 0.18.0
Hope that helps (and the exrm version detection works properly)

**Comment by aaronjensen** [comment]
I tried to use this, but master `edeliver` now depends on `exrm ~> 0.16.0` which is rather old. Could you relax this requirement?

**Comment by mk** [comment]
yes, feel free to open a PR, otherwise we'll take a look as soon as we find the time, hopefully next week.

**Comment by mk** [comment]
sorry, I missed the open PR regarding this, will try to get it merged as soon as we've had the time to test it.

**Comment by bharendt** [comment]
edeliver now supports all exrm version `>= 0.16.0` (see e3f4f8acf8b57a60dfba5c7403d121208e0a8d61) up to the current version [1.0.0-rc5](https://github.com/bitwalker/exrm/releases/tag/1.0.0-rc5)
