### ISSUE TITLE
Documentation of adding LinkConfig plugin to Distillery config 

### ISSUE THREAD

**Issue by tonyvanriet** [boldpoker/edeliver#174]
I got tripped up trying to use `LINK_VM_ARGS` with a Distillery release until I found [this documentation](https://github.com/boldpoker/edeliver/blob/master/lib/distillery/plugins/link_config.ex#L5-L15) in the Distillery LinkConfig plugin.

I felt inclined to add the below section to the [Use per host configuration](https://github.com/boldpoker/edeliver/wiki/Use-per-host-configuration) wiki page at the end, just before the caveats section, but I thought I would mention it here and get somebody's blessing first.

___

#### linking with distillery
In order to link either `sys.config` or `vm.args` while using the distillery release generator, you must add the `LinkConfig` plugin to the `rel/config.exs` distillery config:
```
environment :prod do
  ..
  plugin Releases.Plugin.LinkConfig
end
```

**Comment by bharendt** [comment]
Makes sense. Feel free to add it to the wiki page. Thanks!
