### ISSUE TITLE
After hot-code upgrade phoenix tries to load old asset files.

### ISSUE THREAD

**Issue by NilsLattek** [boldpoker/edeliver#175]
### Environment

* Edeliver version (`mix edeliver --version`): edeliver v1.4.0
* Elixir version (`elixir -v`): Elixir 1.3.4 (Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace])
* Build tool and version (distillery|exrm): distillery 0.10.1
* Operating system (on build / deploy hosts): build & deploy: Ubuntu 16.04.1 LTS, building happens in docker container.
* Are you using an umbrella project (yes|no): no

### Verbose output

* Are there more information when running with `--verbose`?
* Can you narrow down the code line causing the issue when running with `--debug`?
* Please remove any private data from the output before pasting it here (login credentials, ip addresses user names etc.)

### Current behavior

I have a phoenix (v1.2.1) project which I deploy with edeliver.
When running a hot-code upgrade it generates new asset files (css, js, I can see them in the generated release with new hashes), but the index.html/app.html is not updated with the new links. It still uses the old hashes. So after the upgrade the style and script urls are still pointing to the old release. After stopping and restarting the server it uses the new links. So it has something to do with the hot-code upgrade, which does not update the main/layout html file. The file itself has the new urls, but it is not updated during hot-code upgrade.

Not sure if this is a bug in edeliver or distillery.

For asset compilation I am using:

```
pre_erlang_clean_compile() {
  status "Running npm install"
    __sync_remote "
      [ -f ~/.profile ] && source ~/.profile
      set -e
      cd '$BUILD_AT'
      npm install $SILENCE
    "

  status "Running brunch build"
    __sync_remote "
      [ -f ~/.profile ] && source ~/.profile
      set -e
      cd '$BUILD_AT'
      node_modules/brunch/bin/brunch build --production $SILENCE
    "

  status "Running phoenix.digest" # log output prepended with "----->"
  __sync_remote " # runs the commands on the build host
    [ -f ~/.profile ] && source ~/.profile # load profile (optional)
    set -e # fail if any command fails (recommended)
    cd '$BUILD_AT' # enter the build directory on the build host (required)
    # prepare something
    mkdir -p priv/static # required by the phoenix.digest task
    # run your custom task
    APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phoenix.digest $SILENCE
  "
}
```

```
$ mix edeliver upgrade production

EDELIVER MY_APP WITH UPGRADE COMMAND

-----> Upgrading to revision fa64dfb from branch master
-----> Detecting release versions on production hosts
-----> Deploying upgrades to 1 online hosts
-----> Checking whether installed version 0.0.4+253-01cf024 is in release store
-----> Building the upgrade from version 0.0.4+253-01cf024
-----> Authorizing hosts
-----> Validating * version 0.0.4+253-01cf024 is in local release store
-----> Ensuring hosts are ready to accept git pushes
-----> Pushing new commits with git to: root@192.168.99.100
-----> Resetting remote hosts to fa64dfbe016a171e12440babf5b3e19b65eb968c
-----> Cleaning generated files from last build
-----> Checking out fa64dfbe016a171e12440babf5b3e19b65eb968c
-----> Fetching / Updating dependencies
-----> Running npm install
-----> Running brunch build
-----> Running phoenix.digest
-----> Compiling sources
-----> Checking version of new release
mesg: ttyname failed: Inappropriate ioctl for device
-----> Uploading archive of release 0.0.4+253-01cf024 from local release store
mesg: ttyname failed: Inappropriate ioctl for device
-----> Extracting archive my_app_0.0.4+253-01cf024.tar.gz
mesg: ttyname failed: Inappropriate ioctl for device
-----> Removing old releases which were included in upgrade package
mesg: ttyname failed: Inappropriate ioctl for device
-----> Generating release
-----> Removing built release 0.0.4+253-01cf024 from remote release directory
-----> Copying release 0.0.5+256-fa64dfb to local release store
-----> Copying my_app.tar.gz to release store
-----> Upgrading production hosts to version 0.0.5+256-fa64dfb
-----> Authorizing hosts
-----> Uploading archive of release 0.0.5+256-fa64dfb from local release store
-----> Upgrading release to 0.0.5+256-fa64dfb

UPGRADE DONE!
```

### Expected behavior

The hot-code upgrade should use new app.html with correkt links to stylesheet and javascript.

**Comment by hamann** [comment]
@NilsLattek Could it have something to do with https://github.com/phoenixframework/phoenix/pull/1774 or https://github.com/bitwalker/exrm/issues/206?
It seems like some caches need to be busted after hotcode reload

**Comment by NilsLattek** [comment]
Yes thats it! Just tested it. Thanks a lot for pointing me in the right direction, I was only looking through the distillery and edeliver issues... 🙈

**Comment by hamann** [comment]
@NilsLattek Nice! Could you please explain how you solved it? I'm sure this issue will pop up again :)

**Comment by NilsLattek** [comment]
Sure, edit config/prod.exs:
```
config :my_app, MyApp.Endpoint,
  http: [port: 4000],
  url: [host: "localhost", port: 4000],
  cache_static_manifest: "priv/static/manifest.json",
  server: true,
  # add these two lines:
  root: ".",
  version: Mix.Project.config[:version]
```
