### ISSUE TITLE
refusing to update checked out branch: refs/heads/master error

### ISSUE THREAD

**Issue by mspanc** [boldpoker/edeliver#20]
It seems that now edeliver does not handle well cases when SSH connection was dropped.

I've tried to run my build twice:

```
vagrant@trusty64:/vagrant$ mix edeliver build release

BUILDING RELEASE OF PLUMBER APP ON BUILD HOST

-----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
-----> Pushing new commits with git to: app@edeliver.stag.srv.myapp.org
-----> Resetting remote hosts to 97f757b0fee0f7ac7602152472cf11bc301bc346
-----> Stashing build directory on remote build host
-----> Fetching / Updating dependencies
-----> Compiling sources
-----> Generating release

FAILED  1:
ssh -o ConnectTimeout=3 app@edeliver.stag.srv.myapp.org
    set -e
    [ -f ~/.profile ] && source ~/.profile
    cd /app/myapp/build &> /dev/null
    if [ "mix" = "rebar" ]; then
      echo "using rebar to generate release" &> /dev/null
      ./rebar   -f generate &> /dev/null
    elif [ "mix" = "relx" ]; then
      echo "using relx to generate release" &> /dev/null
      ./relx release &> /dev/null
    elif [ "mix" = "mix" ]; then
      echo "using mix to generate release" &> /dev/null
      MIX_ENV=prod mix release &> /dev/null
    fi

   &> /dev/null

vagrant@trusty64:/vagrant$ mix edeliver build release

BUILDING RELEASE OF PLUMBER APP ON BUILD HOST

-----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
-----> Pushing new commits with git to: app@edeliver.stag.srv.myapp.org
-----> Resetting remote hosts to 97f757b0fee0f7ac7602152472cf11bc301bc346
-----> Stashing build directory on remote build host

FAILED  1:
ssh -o ConnectTimeout=3 app@edeliver.stag.srv.myapp.org
    set -e
    [ -f ~/.profile ] && source ~/.profile
    cd /app/myapp/build &> /dev/null
    [[ $(git stash list | wc -l) -gt 0 ]] && _oldest_stash=$(git stash list | tail -1 | grep -o 'stash@{[0-9]\+}' | grep -o '[0-9]\+') || _oldest_stash=0
    [[ ${_oldest_stash} -gt 50 ]] && git stash drop stash@{$_oldest_stash} &> /dev/null
    git stash --all &> /dev/null
   &> /dev/null
```

And then, for the next time I got the following error:
 
```
-----> Pushing new commits with git to: app@edeliver.stag.srv.myapp.org
remote: error: refusing to update checked out branch: refs/heads/master
remote: error: By default, updating the current branch in a non-bare repository
remote: error: is denied, because it will make the index and work tree inconsistent
remote: error: with what you pushed, and will require 'git reset --hard' to match
remote: error: the work tree to HEAD.
remote: error:
remote: error: You can set 'receive.denyCurrentBranch' configuration variable to
remote: error: 'ignore' or 'warn' in the remote repository to allow pushing into
remote: error: its current branch; however, this is not recommended unless you
remote: error: arranged to update its work tree to match what you pushed in some
remote: error: other way.
remote: error:
remote: error: To squelch this message and still keep the default behaviour, set
remote: error: 'receive.denyCurrentBranch' configuration variable to 'refuse'.
To app@edeliver.stag.srv.myapp.org:/app/myapp/build
 ! [remote rejected] master -> master (branch is currently checked out)
error: failed to push some refs to 'app@edeliver.stag.srv.myapp.org:/app/myapp/build'
```

Removing and cloning the repo again on the target machine resolves the issue. It would be nice if edeliver cleaned up repo by itself in case of trouble.

I must admit that the generally speaking, requirement to have valid, cloned git repo on the target machine is a trouble-maker. 

First of all, while provisioning build servers you must clone the repo, which forces you to use different authentication scheme to clone it from git than one that is used by the developers on a daily basis.

Than you must ensure that it is valid to avoid problems mentioned before.

Wouldn't it be just easier to always clone fresh repo before building starts and use SSH key forwarding to ensure that developer's credentials are used?

**Comment by mspanc** [comment]
Getting more and more cumbersome errors:

```
-----> Stashing build directory on remote build host

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <app@edeliver.stag.srv.myapp.org>) not allowed
Cannot save the current index state
```

Workaround is also re-cloning the repo.

**Comment by bharendt** [comment]
Edeliver __stashes all changes__ from previous builds on the build host before building the next time.
I think, in your case this __failed during your second build__, because git asked __interactively__ to set the git `user.name` and `user.email`.
You __have to run these git configuration commands once on each build host__ as the build user:

	  git config --global user.email "you@example.com"
	  git config --global user.name "Your Name"
	  
See __"Configuration"__ section of the [README](https://github.com/boldpoker/edeliver/blob/master/README.md).

Maybe that is what you did, when you recloned the repository?

__I dind't find a way how to disable that message yet__. Maybe we can use just dummy values as `name` and `email` for the `git stash` command, if that is the onliest command which requires that.

Actually __it should be possible__ to push the first time to the build host __without cloning the repository manually__. I will check that and fix it if necessary. Thanks for your report.

**Comment by hamann** [comment]
@mspanc 
We're currently having a similiar issue where every deploy after the initial clone is failing with the same error message as you listed above.
Instead of cloning the repository the following steps could work:

on remote host:

```sh
$ mkdir $remote_git_dir
$ cd $remote_git_dir
$ git init .
$ config receive.denyCurrentBranch ignore
```
and then 

```sh
$ mix edeliver build release
```

Can you confirm that?

**Comment by mspanc** [comment]
I will check this out after the weekend.

**Comment by mspanc** [comment]
It seems to work, thanks!
