### ISSUE TITLE
`mix edeliver build upgrade` should exit non-zero if it fails:

### ISSUE THREAD

**Issue by aaronjensen** [boldpoker/edeliver#29]
expect a non-zero exit code, got zero

```
BUILDING UPGRADE OF BOOKING APP ON BUILD HOST

-----> Authorizing hosts
-----> Validating * version 1.0.0-16-g9aa99a2 is in s3 release store
-----> Ensuring hosts are ready to accept git pushes
-----> Pushing new commits with git to: deploy@mysite.com

FAILED  1:
git push --tags -f deploy@mysite.com edge &> /dev/null
```

**Comment by bharendt** [comment]
actually it should. see: https://github.com/boldpoker/edeliver/blob/master/libexec/common#L90, https://github.com/boldpoker/edeliver/blob/master/libexec/core#L238 and https://github.com/boldpoker/edeliver/blob/master/libexec/output#L66

**Comment by aaronjensen** [comment]
The problem is the mix task. If you run `mix edeliver` it always succeeds.

**Comment by aaronjensen** [comment]
Though I have been thinking about just using the script directly, that seems like the way to go.
