### ISSUE TITLE
Support incremental build?

### ISSUE THREAD

**Issue by aaronjensen** [boldpoker/edeliver#31]
At the moment, edeliver always cleans. I'm not experienced with elixir enough to know that this is necessary, but I do know that it greatly increases build time. I wonder if we should make it optional?

**Comment by mk** [comment]
I think we'll add a `--skip-clean` option. I'm pretty sure we had issues when not cleaning at times that old code was still used. Once we know we can safely omit the clean step we can default to it.

**Comment by aaronjensen** [comment]
We ran into issues when not changing versions of dependencies that we pulled in via git, but that was whether or not we cleaned.

I tried removing the `mix clean` here https://github.com/substantial/edeliver/commit/d91b03ef383cbb17b1c39ec96b8dc7a6bfe9be13 but that didn't seem to do the trick. Is there something else that nukes the entire build directory or something? I couldn't find it.

**Comment by mk** [comment]
I think that's because of the `git stash --all` wich also stashes all files in `.gitignore` (usually also the `_build` dir). We want to remove the `--all` option, see #28.

**Comment by mk** [comment]
We'll get rid of the `git stash --all` command. I still think it should be the default to clean the repository using `git clean -fdx` because there can be issues with old files in the repository otherwise. We're thinking of providing an override for passing folders to clean so one can customize what is removed.

**Comment by bharendt** [comment]
Added __command line option__ `--skip-git-clean` to skip the step when the repository is reset to a clean state. If that option is used, the `_build`, `rel` and `deps` folders and all other generated files are __not cleaned__ before the next build is started to __decrease build time__.
Optionally __the pathes__ that should be __cleaned__ can be __adjusted__ in the config file by the `GIT_CLEAN_PATHS` option, e.g. by setting it to `="_build rel priv/static/generated"`.
When the option `--skip-mix-clean` is used in addition, the build process will be fully __incremental__.
To make `--skip-git-clean` the default, you can set `SKIP_GIT_CLEAN="true"` in the config, same with `SKIP_MIX_CLEAN="true"`

**Comment by aaronjensen** [comment]
Awesome, thanks for all the great fixes lately. I saw you cut 1.1.0, could you also release it to hex please when you get a chance? Thanks!

**Comment by mk** [comment]
We've just released 1.1.1 and it's finally available on hex.pm: https://hex.pm/packages/edeliver/1.1.1

Thanks for your help @aaronjensen!
