### ISSUE TITLE
Bypass prompt for release type?

### ISSUE THREAD

**Issue by aaronjensen** [boldpoker/edeliver#32]
If I have a release and an upgrade of a specific version and I use `deploy release` edeliver will ask me if I want to upgrade or release. If I wanted to upgrade, I would have specified `upgrade`. 

Is there a way to force it to use `release`? I can't use it in CI if I'm asked questions like this.

**Comment by bharendt** [comment]
__Upgrade__ packages built with __exrm also contain__ the __full release__. If rebar is used as build tool, this is not the case and upgrade packages can only be used for hot code upgrades.
So if you are using exrm as build tool and build an __upgrade__ package __and__ an __release__, you can deploy both as release. 
If both exist, we could chose the `release` automatically, if the `--force` or `--plain` options is used or
add a `-yes` option to disables all interaction.

**Comment by aaronjensen** [comment]
Any of those options would be great. Something that disabled all interaction would be helpful for scripting. Are you saying that those options could be added or should any of those work today?

**Comment by mk** [comment]
I think the way to go is to remove the prompt in case there's a release and an upgrade and just prefer the release.

**Comment by aaronjensen** [comment]
We did this https://github.com/substantial/edeliver/commit/03d0cf4a0118d49b8f9e58c24bc3cbadf08d515f

**Comment by mk** [comment]
Cool, I think it would still be nice if edeliver would use the upgrade release in case there's no release available.
