### ISSUE TITLE
Need to pull sources manually when deploying

### ISSUE THREAD

**Issue by alg** [boldpoker/edeliver#35]
Hi guys, I'm facing a problem. When deploying, each time before I run `mix edeliver build release` I need to go and `git pull` the sources on the build node. If I don't do this, I get this:

```
 → mix edeliver build release -V

BUILDING RELEASE OF ROCKSTAR APP ON BUILD HOST

-----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
-----> Pushing new commits with git to: alg@xyz.com
remote: error: refusing to update checked out branch: refs/heads/master
remote: error: By default, updating the current branch in a non-bare repository
remote: error: is denied, because it will make the index and work tree inconsistent
remote: error: with what you pushed, and will require 'git reset --hard' to match
remote: error: the work tree to HEAD.
remote: error:
remote: error: You can set 'receive.denyCurrentBranch' configuration variable to
remote: error: 'ignore' or 'warn' in the remote repository to allow pushing into
remote: error: its current branch; however, this is not recommended unless you
remote: error: arranged to update its work tree to match what you pushed in some
remote: error: other way.
remote: error:
remote: error: To squelch this message and still keep the default behaviour, set
remote: error: 'receive.denyCurrentBranch' configuration variable to 'refuse'.
To alg@xyz.com:/home/alg/builds/rockstar
 ! [remote rejected] master -> master (branch is currently checked out)
error: failed to push some refs to 'alg@xyz.com:/home/alg/builds/rockstar'

FAILED 1:
git push --tags -f alg@xyz.com master
```

Is this by intention that I need to go pull the updates first, or is it something that I missed during the setup? I just scp'ed my sources initially to the build server.

UPDATE: I found #20. Is it the only way to handle this -- to `config receive.denyCurrentBranch ignore`?

I wonder if you have any better ideas? I could spend some time on it.

**Comment by mk** [comment]
Hey, that seems strange. You shouldn't have to scp your sources to the build server, edeliver should do that for you. Can you remove that directory and try again? Thanks!

**Comment by alg** [comment]
Hm. You were right. This is really odd. I don't expect it to solve the issue with building updates, am I right?

**Comment by alg** [comment]
In fact it did. Sorry for bothering you with this! Solved.

**Comment by mk** [comment]
Great to hear! Let us know if you run into any other issues.

**Comment by alg** [comment]
Thanks!
