### ISSUE TITLE
unfork repository?

### ISSUE THREAD

**Issue by aaronjensen** [boldpoker/edeliver#40]
Hi there, I think that edeliver has sufficiently changed from deliver such that it should no longer be considered a fork. Would you consider making edeliver not a fork? My primary concern is that forked repositories' code can't be searched, so it is annoying to search for things (I have to do it locally instead of on github)

**Comment by mk** [comment]
Makes sense. What's the best way to do this that will preserve the issues etc?

**Comment by bharendt** [comment]
I also agree. It would be also better for pull requests which go to the main repository by default.

**Comment by kommen** [comment]
I think the only way to unfork is to contact github support.

**Comment by mk** [comment]
I've contacted github support. Will keep you posted once I hear back.

**Comment by mk** [comment]
GitHub just unforked the repo, thanks!

**Comment by aaronjensen** [comment]
That was quick, awesome!
