### ISSUE TITLE
Possible to have app in subdir of repo?

### ISSUE THREAD

**Issue by aaronjensen** [boldpoker/edeliver#49]
Our repo has the app & mix.exs in a sub directory rather than the top level directory. Is there a setting for this? It doesn't appear to work out of the box.

**Comment by bharendt** [comment]
At the moment there is no option to allow this, but maybe we should add this to support repositories with multiple apps or mono-repositories.

But for now you could try to set the `BUILD_AT` path in your config to `/foo/project` when you build the first time. Edeliver will then initialize the git repository on the build host for you but fail when building. If you then change the `BUILD_AT` config to `/foo/project/subdir` pushes should still work for further builds but building should be done in the correct subdirectory on the build host. 

Let us known if this works as a start or if you encounter further problems with that.

**Comment by bharendt** [comment]
If it works, you can automate this step to initialize the git repository at a different location and keep the `BUILD_AT` config set to `/foo/project/subdir` by adding two hooks to your config:

```sh
pre_init_app_remotely() {
  ACTUAL_PROJECT_DIR="$DELIVER_TO"
  DELIVER_TO="$(dirname $DELIVER_TO)"
}

post_init_app_remotely() {
 DELIVER_TO="$ACTUAL_PROJECT_DIR" 
}

```

**Comment by bharendt** [comment]
I think you need the two hooks in any case, because edeliver [automatically adjust the repository path, if it changed](https://github.com/boldpoker/edeliver/blob/master/libexec/common#L128).

**Comment by aaronjensen** [comment]
Ok, so this works with one caveat. The first build appears to not work. For some reason the `BUILD_AT` directory is empty except for the `.git`. That caused:

```
[16:31:22]bash: line 2: cd: /tmp/erlang/my_app/staging/builds/my_subdir: No such file or directory
```

If I manually go to the builds directory and `git reset --hard` then the build works next time.

**Comment by bharendt** [comment]
Then it would probably help if the build directory is not reset already in `post_init_app_remotely`, but in `pre_erlang_get_and_update_deps`. Then all git operations will be executed in the actual git directory, not in the application subdirectory:

```sh
pre_init_app_remotely() {
  ACTUAL_PROJECT_DIR="$DELIVER_TO"
  DELIVER_TO="$(dirname $DELIVER_TO)"
}

pre_erlang_get_and_update_deps() {
  DELIVER_TO="$ACTUAL_PROJECT_DIR" 
}

```

**Comment by aaronjensen** [comment]
That seemed to help, thanks @bharendt

**Comment by atonse** [comment]
Hi I tried this but I'm not even able to build the project to begin with. Copying those lines above didn't help at all.

My project has a layout:

root
- client (ember app)
- server (elixir/phoenix app)

I set BUILD_AT="/tmp/erlang/stractegize/builds" when initializing
then, I set it to BUILD_AT="/tmp/erlang/stractegize/builds/server"

And then I get this:

```-----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
-----> Pushing new commits with git to: deploy@qa.stractegize.com
-----> Resetting remote hosts to e8a1737bde5f87c5ce6001c549c7697daf4b79b0
-----> Cleaning generated files from last build
-----> Fetching / Updating dependencies
using mix to fetch and update deps
rebar for mix was built already
* creating /home/deploy/.mix/archives/hex-0.11.5.ez
** (Mix) Could not find a Mix.Project, please ensure a mix.exs file is available```

**Comment by bharendt** [comment]
Hi @atonse. Did you try with the both pre-hooks as mentioned above? Running edeliver initially (once) with `BUILD_AT` set to `"/tmp/erlang/stractegize/builds"` (not containing the subproject dir) should actually not be necessary then any more.
The git operations (push to build host, reset, and clean) in your output seem to work, but the error `Could not find a Mix.Project, please ensure a mix.exs file is available` indicates that the `BUILD_AT` path is actually not set correctly to one of the sub dirs (`.../server` or `.../client`) when the dependencies are fetched. Maybe you could try with a config like that:


```sh
# .deliver/config

[[ -z "$APP" ]] && echo "${txtred}APP env missing!${txtrst}" \
                && echo "Please use the env APP=client|server" && exit 1

[[ "$APP" != "client" && "$APP" != "server" ]] \
                && echo "${txtred}Unknown APP env '$APP'!${txtrst}" \
                && echo "Please use the env APP=client|server" && exit 1

BUILD_HOST="..."
BUILD_USER="..."
...

# use either '.../server' or '.../client'  as app subdir
BUILD_AT="/tmp/erlang/stractegize/builds/${APP}"

pre_init_app_remotely() {
  # use parent dir (of '.../client' or '.../server' subdir) for git operations
  # in that case: '/tmp/erlang/stractegize/builds'. 
  # $DELIVER_TO is set by edeliver from $BUILD_AT
  ACTUAL_PROJECT_DIR="$DELIVER_TO" # store the project subdir for build operations
  DELIVER_TO="$(dirname $DELIVER_TO)" # use parent dir for git operations
}

pre_erlang_get_and_update_deps() {
  # restore project dir to sub dir '.../server' or '.../client', in that case:
  # '/tmp/erlang/stractegize/builds/server' or '/tmp/erlang/stractegize/builds/client'
  DELIVER_TO="$ACTUAL_PROJECT_DIR" 
}
```

This should also enable you to build both, the client and the server if you pass the `APP` env to edeliver like:

```sh
  APP=server mix edeliver build release
  # or
  APP=client mix edeliver build release
```

**Comment by aaronjensen** [comment]
This was working for us until we started to use `mix edeliver upgrade`, now as part of the upgrade step when attempting to upgrade production, for some reason this happens:

```
[16:56:39]-----> Upgrading production hosts to version 3.0.0+master-11886-b04bd9e
[16:56:39]-----> Authorizing hosts
[16:56:39]-----> Uploading archive of release 3.0.0+master-11886-b04bd9e from s3 release store
[16:56:39]bash: line 3498: warning: here-document at line 5 delimited by end-of-file (wanted `EOF#!/usr/bin/perl')
[16:56:39]bash: line 3498: warning: here-document at line 5 delimited by end-of-file (wanted `EOF#!/usr/bin/perl')
[16:56:45]-----> Upgrading release to 3.0.0+master-11886-b04bd9e
[16:56:45]bash: line 4: bin/booking: No such file or directory
[16:56:45]
[16:56:45]FAILED  1:
[16:56:45]ssh -o ConnectTimeout=3 deploy@23.253.235.155 
[16:56:45]    [ -f ~/.profile ] && source ~/.profile
[16:56:45]    set -e
[16:56:45]    cd /tmp/erlang/booking/production/builds/booking/booking 
[16:56:45]    bin/booking upgrade 3.0.0+master-11886-b04bd9e 
[16:56:45]   
[16:56:45]bash: line 4: bin/booking: No such file or directory
```

Where /tmp/erlang/booking/production/builds/booking is actually our BUILD_AT, so it shouldn't be running there.

**Comment by bharendt** [comment]
I think this even has nothing to do with the subdirectory. Does that fix this:

**Comment by aaronjensen** [comment]
@bharendt ah, that'd help. That said, I couldn't get `upgrade` to actually work at all, even on staging. i just thought it was working because i didn't get an error.

**Comment by bharendt** [comment]
No, `upgrade` for staging worked, because the `DEPLOY_AT` [dir was correctly (re)set](https://github.com/boldpoker/edeliver/blob/23cdf71/libexec/erlang#L47) to `TEST_AT`, [but not for the `production` env](https://github.com/boldpoker/edeliver/blob/23cdf71/libexec/erlang#L43). There it would not help to set `DEPLOY_AT="$DEPLOY_AT"`, that's why it must be stored before [building the upgrade](https://github.com/boldpoker/edeliver/blob/dc9f6ac6b52a8d8a6ec7c154a4276cfa22dbb3a4/strategies/erlang-upgrade#L114) and restored [before deploying the upgrade](https://github.com/boldpoker/edeliver/blob/dc9f6ac6b52a8d8a6ec7c154a4276cfa22dbb3a4/strategies/erlang-upgrade#L153).

**Comment by aaronjensen** [comment]
Unfortunately, it didn't work for us. I do not see any log messages that I normally see when an upgrade happens. I mentioned in another issue that we moved back to a manual dual step process and that worked.

**Comment by bharendt** [comment]
Added a [wiki page](https://github.com/boldpoker/edeliver/wiki/Mono-Repository---App-in-Subdirectory) about how to configure edeliver if the app is in a subdirectory of the project and how to build and deploy [umbrella projects](https://github.com/boldpoker/edeliver/wiki/Umbrella-Projects) using edeliver.
