### ISSUE TITLE
Can't find repo module

### ISSUE THREAD

**Issue by AaronBetterOfficeApps** [boldpoker/edeliver#50]
I have been trying to run database migrations on a staging and production server. Our app has to connect too and read from several databases but only writes to one.

I have added to following line the `config` file, with the repo that I need to run migrations for.
`ECTO_REPOSITORY="MyApp.Repo"`

but I keep getting the following error when I run `mix edeliver migrate staging`

```
==> No ecto repository module found.
Please specify the repository in the edeliver config as ECTO_REPOSITORY env.
<<"error">>
```

**Comment by bharendt** [comment]
Using `ECTO_REPOSITORY` env or setting it in the config should work now. But the actual question is, why the repository module cannot be found automatically. Edeliver searches for a module that exports the `__repo__/0` function. So maybe you could check what `MyApp.Repo.module_info(:exports) |> Dict.fetch(:__repo__)` returns on your staging node.

**Comment by AaronBetterOfficeApps** [comment]
Thanks!
