### ISSUE TITLE
Errors swallowed by pre_erlang_clean_compile

### ISSUE THREAD

**Issue by kyledecot** [boldpoker/edeliver#51]
When attempting to use the example `pre_erlang_clean_compile` hook on the [Run additional build tasks](https://github.com/boldpoker/edeliver/wiki/Run-additional-build-tasksl) page any errors that happen are essentially swallowed and the build appears to succeed. For example in the case that `priv/static` is ignored by git (default for phoenix applications) you'll receive the following:

> The input path "priv/static" does not exist

The only way to know this however is to run this command manually inside of the `BUILD_AT` directory

**Comment by bharendt** [comment]
If you use `__sync_remote` and `set -e` it should actually fail if any command executed on the build host fails. For any other command executed in a pre/post hook, you should call `error "message"` if any command failed, e.g like that: `do_something || error "something failed"`.

**Comment by kyledecot** [comment]
@bharendt after looking a little more closely it would appear that the "error" still exists with status code `0`. I'm not sure this is the intended behavior so I went ahead and put in an issue at https://github.com/phoenixframework/phoenix/issues/1573

In any case should the example include a `mkdir priv/static` just in case the directory doesn't exist?

**Comment by bharendt** [comment]
True, the `phoenix.digest` task should fail in that case with a status code `!= 0`. I updated the example and added the `mkdir`. Thanks for the hint.
