### ISSUE TITLE
Response from edeliver commands truncated

### ISSUE THREAD

**Issue by andruby** [boldpoker/edeliver#54]
When running an edeliver command (such as `mix edeliver migrate staging up`) the reponse seems to be  truncated.

![1 tmux 2016-04-08 13-58-06](https://cloud.githubusercontent.com/assets/10639/14382945/fe7f49e4-fd91-11e5-97e9-217cba9acb94.png)

How can I get the full response?

**Comment by bharendt** [comment]
You can try with the `--verbose` option, but actually the value in the `response:` line should contain the full output anyway. We will investigate that. Also the edeliver command should fail if there is an error during the migration, or was the migration actually successful?

**Comment by andruby** [comment]
`--verbose` did not add any extra output. Running with `--debug` I did however find that the remote job being executed is : `bin/gonzo rpc Elixir.Edeliver run_command '\''[[migrate, "gonzo", up]].'\'' | tail -1` (the `tail -1` seems to be the culprit.

If I'm not mistaken that command is built in `edeliver/strategies/erlang-node-execute`.

Could we just remove the `tail -1` or does it perform a required function?

**Comment by bharendt** [comment]
True, the output [is tailed](https://github.com/boldpoker/edeliver/blob/e50c94025462ae4166f64f3b4a51c5323db6267c/strategies/erlang-node-execute#L23) because the first line of the output now contains the actual version of the run script that is used, [printed by the start script generated by exrm](https://github.com/bitwalker/exrm/blob/fa1d2c91cae167731a328102568d5ce6c71302ba/priv/rel/files/boot_shim#L10). We will change that and output everything except the first line instead. As a quickfix you can remove that part of the command in your local edeliver copy (`.deps/edeliver/strategies/erlang-node-execute:23` or run the migration command manually on your node: 

```
  cd $APP_DIR
  APP=my_app
  bin/$APP rpc Elixir.Edeliver run_command "[[migrate, \"$APP\", up $VERSION]]."
```

**Comment by bharendt** [comment]
@andruby: If you get more detailed output now, maybe your issue is also related to #50 and maybe you can help use figuring out why the repository module sometime can not be found. And thanks for reporting this issue.

**Comment by andruby** [comment]
When I run the command manually on my node I get another error:

```bash
/var/www/gonzo# ./bin/gonzo rpc Elixir.Edeliver run_command "[[migrate, \"gonzo\", \"up\"]]."
Using /var/www/gonzo/releases/0.1.2/gonzo.sh
RPC to 'gonzo@127.0.0.1' failed: {'EXIT',
                                  {function_clause,
                                   [{'Elixir.Edeliver',migrate,
                                     [gonzo,<<"0.1.2">>,"up",all],
                                     [{file,"lib/edeliver.ex"},{line,36}]},
                                    {rpc,'-handle_call_call/6-fun-0-',5,
                                     [{file,"rpc.erl"},{line,206}]}]}}
```

I tried it with version and without, I get the same error.

**Comment by bharendt** [comment]
Sorry, `up` needs to be an erlang atom, not a string.

**Comment by andruby** [comment]
Now I get the same last line as in the tailed output:

```bash
./bin/gonzo rpc Elixir.Edeliver run_command "[[migrate, \"gonzo\", up]]."
Using /var/www/gonzo/releases/0.1.2/gonzo.sh
RPC to 'gonzo@127.0.0.1' failed: {'EXIT',
                                  {#{'__exception__' => true,
                                     '__struct__' => 'Elixir.Postgrex.Error',
                                     connection_id => 24352,
                                     message => nil,
                                     postgres => #{code => undefined_object,
                                       file => <<"parse_type.c">>,
                                       line => <<"205">>,
                                       message => <<"type \"jsonb\" does not exist">>,
                                       pg_code => <<"42704">>,
                                       position => <<"50">>,
                                       routine => <<"typenameType">>,
                                       severity => <<"ERROR">>}},
                                   [{'Elixir.Ecto.Adapters.SQL','query!',5,
                                     [{file,"lib/ecto/adapters/sql.ex"},
                                      {line,185}]},
                                    {'Elixir.Ecto.Adapters.Postgres',
                                     '-execute_ddl/3-fun-0-',4,
                                     [{file,"lib/ecto/adapters/postgres.ex"},
                                      {line,56}]},
                                    {'Elixir.Enum',
                                     '-reduce/3-lists^foldl/2-0-',3,
                                     [{file,"lib/enum.ex"},{line,1473}]},
                                    {'Elixir.Ecto.Migration.Runner',flush,0,
                                     [{file,"lib/ecto/migration/runner.ex"},
                                      {line,87}]},
                                    {timer,tc,2,
                                     [{file,"timer.erl"},{line,181}]}]}}
```

And now I know what the problem is. The server is running Postgresql 9.3, which does not yet support jsonb (added in 9.4).

Thanks @bharendt for helping me run the command manually. Let me know if I can help fix the tail -1. FYI `tail -n +2` shows all lines except the first.

**Comment by bharendt** [comment]
Thanks for helping to improve edeliver. This is fixed already in the master, but we will publish a new hex version soon.
