### ISSUE TITLE
allow for private dependencies

### ISSUE THREAD

**Issue by stocks29** [boldpoker/edeliver#55]
it would be great if this library provided a way to handle private dependencies. that is, dependencies that can't be fetched from the build server but are present when the build command is kicked off.

**Comment by bharendt** [comment]
You could try maybe one of the following options. They should work if [mix](http://elixir-lang.org/docs/stable/mix/Mix.html) is used as build tool but most of them should also work if rebar is used. 

- 1.) Install your libary which is a private dependeny on your build host e.g at `/usr/lib/your_private_dep` (and preferably on your development hosts at the same location) and use the mix `path:` [option](http://elixir-lang.org/docs/stable/mix/Mix.Tasks.Deps.html) for your dependency:


       ```elixir
       # mix.exs
       defmodule YourApp.Mixfile do
         use Mix.Project

         def project do
          [
            app: :your_app,
            deps: [
              {:phoenix_html, "..."}, # mix dependency
              {:your_private_dep, path: "/usr/lib/your_private_dep"}, # path dependency
              ....

       ```

       I am not sure whether relative locations like `~/your_private_dep` would work too.
  
- 2.) Use an edeliver [pre-hook](https://github.com/boldpoker/edeliver/wiki/Run-additional-build-tasks) in your `.deliver/config` which somehow gets the dependency:

      ```sh
        # .deliver/config
        ...
        pre_erlang_get_and_update_deps() {
          __sync_remote " # execute on build host
            # e.g. copy the dependency from some source on the build host
            cp -R /usr/lib/your_private_dep ${BUILD_AT}/deps/your_private_dep $SILENCE
            # or fetch it from some other scp / s3 / xy location
          "
        }
      ```

- 3.) Link your dependency in `deps/your_private_dep` pointing to `/usr/lib/your_private_dep` and commit that link to your repository:

      ```sh
        ln -s /usr/lib/your_private_dep ./deps/your_private_dep
        git add -f ./deps/your_private_dep
        git commit -m "linking private dep"
      ```

- 4.) Implement your own [mix scm](https://github.com/elixir-lang/elixir/tree/master/lib/mix/lib/mix/scm) which fetches your private dependency somehow:

     ```elixir
     # mix.exs
     Code.require_file "lib/mix/my_scm.exs", __DIR__
     Mix.SCM.append  MyApp.SCM.MySCM
     defmodule YourApp.Mixfile do
       use Mix.Project

       def project do
        [
          app: :your_app,
          deps: [
            {:your_private_dep, download: "url"}, # private dependency using your own scm, e.g download it 
      ...
      ```


      ```elixir
      # lib/mix/my_scm.exs
      defmodule MyApp.SCM.MySCM do
        @behaviour Mix.SCM
        @moduledoc false

        def fetchable?, do: true
        def format(opts), do: opts[:download]
        def format_lock(_opts), do: {:download, true}

        def accepts_options(_app, opts) do
          case opts[:download] do
            <<_,_::binary>> -> opts
            _ -> nil
          end
        end

        def checked_out?(opts) do
          File.dir?(opts[:dest])
        end

        def checkout(opts) do
          # somehow fetch your private library, e.g. download from internal net
        end

        def lock_status(_opts), do: :ok
        def equal?(opts1, opts2), do: opts1[:download] == opts2[:download]
        def managers(_opts), do: []
        def update(opts), do: checkout(opts)
      end
    ```

- 5) Use a private repository containing your private library

    ```elixir
     # mix.exs
     defmodule YourApp.Mixfile do
       use Mix.Project

       def project do
        [
          app: :your_app,
          deps: [
            {:your_private_dep, github: "path/to/your_private_repo"},
    ```
    
    And install the private / secret git ssh key on the build host or configure your build 
    host (on your development host) to use agent forwarding e.g like this:

    ```
    Host your.build.host
    IdentityFile ~/.ssh/your-github-secret-key
    ForwardAgent yes
    ```

Option two (edeliver-pre-hook) and option three (linking the dep) might require to add your dependency as "fake" hex, path or git dependency to the `deps` config in your `mix.exs` to force mix to compile them,
but as long as the version matches they should not be fetched by mix and the linked / copied dependency would be used instead. 

When using option one (file dependency) or three (linking the dep) you must keep your private library up to date yourself on the build host (and all development hosts). 

Hope that helps and if there are any other suggestions, please let us know.

**Comment by bharendt** [comment]
I [added this information to a wiki page](https://github.com/boldpoker/edeliver/wiki/Private-Dependencies), so I will close this issue.

**Comment by stocks29** [comment]
Cool, thanks!
