### ISSUE TITLE
Ecto 2.0 and missing __repo__/0

### ISSUE THREAD

**Issue by talklittle** [boldpoker/edeliver#61]
Ecto 2.0 removes the `__repo__/0` function from Ecto.Repo, so edeliver fails to detect Repos when running e.g.:

    mix edeliver migrate production

**Comment by bharendt** [comment]
@talklittle Thanks a lot. I think this solves also [that issue](https://github.com/boldpoker/edeliver/issues/50). It was submitted right after the ecto release [2.0.0-beta.1](https://hex.pm/packages/ecto/2.0.0-beta.1) was published. This fix is included in the [edeliver 1.2.4 release](https://hex.pm/packages/edeliver/1.2.4).

**Comment by talklittle** [comment]
@bharendt Great! Thanks for the fast response.
