### ISSUE TITLE
deploy release command shows upgrades

### ISSUE THREAD

**Issue by gaynetdinov** [boldpoker/edeliver#67]
`mix edeliver deploy release to staging` shows a list of releases AND upgrades, while `mix edeliver deploy upgrade to staging` shows only upgrades.

**Comment by bharendt** [comment]
The reason for that is, that upgrades generated by exrm can be also used / deployed as releases. They contain the full release, in addition to the modules / files to upgrade.

**Comment by gaynetdinov** [comment]
ok, thanks for the quick reply!
