### ISSUE TITLE
mix edeliver upgrade staging does not respect the TEST_AT to DEPLOY_TO fallback

### ISSUE THREAD

**Issue by aaronjensen** [boldpoker/edeliver#76]
If `TEST_AT` is not set, `mix edeliver upgrade staging` does not use `DEPLOY_TO`, but I would expect it to. For now we are just setting `TEST_AT` as well, but this was surprising to us as the readme claims it should.

**Comment by bharendt** [comment]
`TEST_AT` is actually set [here](https://github.com/boldpoker/edeliver/blob/23cdf71605d9f15b4716492c909862b8f4e30512/libexec/erlang#L65) to `DELIVER_TO` as default which is [invoked when deploying the upgrade](https://github.com/boldpoker/edeliver/blob/f70ab1266029b561f329f9b56260ab3b442143d5/strategies/erlang-deploy-upgrade#L3). So at the moment I don't see why it should not work, except if `TEST_AT` would be an empty string or something.

**Comment by aaronjensen** [comment]
Not sure, we're not setting it at all. it works for other commands, but fails for `mix edeliver upgrade` (we can see it attempt to cd to `/booking` instead of `$DELIVER_TO/booking`

**Comment by aaronjensen** [comment]
Also, it's the upgrade command and the problem is right away when checking for the node version, so maybe that needs to be included in https://github.com/boldpoker/edeliver/blob/f70ab1266029b561f329f9b56260ab3b442143d5/strategies/erlang-upgrade as well

**Comment by bharendt** [comment]
True, it is missing there. Thanks

**Comment by bharendt** [comment]
This is included in version `1.2.6`.
