### ISSUE TITLE
No easy way to build and release when there are multiple releases built already with auto versioning

### ISSUE THREAD

**Issue by aaronjensen** [boldpoker/edeliver#77]
There doesn't seem to be an easy way to build and release as you're forced to pick a version number. Given that the version number generation when you're using auto versioning happens on the build server, it's a little tricky to get the latest built version.

In other words:

```bash
  mix edeliver build release --branch=$BRANCH
  mix edeliver deploy release to $DELIVER_ENV --version=$TARGET_VERSION
```

How do we get TARGET_VERSION? For now, we are doing this:

```bash
  TARGET_VERSION=$(ssh $BUILD_USER@$BUILD_HOST "cat $BUILD_AT/rel/$APP/releases/start_erl.data 2>/dev/null | cut -d' ' -f2")
```

This works, but it'd be nice if there were a compound command that could do this or if there were some easy way to get the latest built version out (without saving the output, grepping and cutting...)

**Comment by bharendt** [comment]
If you use `AUTO_VERSION=commit-count-branch+branch+revision` you would be able to see which version is the most recent one for the given branch.
But I also think something like `--version=latest` would be quite helpful and your proposal to get it from the build host is maybe one suitable option for that.

And I think the version selection could be improved in general by

- displaying only the last x items (but allow to increase the number)
- allow to select a version by a single key, e.g. `1` for the most recent version and `2` for the version before etc, because typing somthing like `1.2.3+2984-foo-branch-f134a67` is not so comfortable
- allow to display info about the last x commits included into the version if the version contains the git-revision, e.g. by typing somthing like `i 2`

**Comment by aaronjensen** [comment]
We automate the process of build then deploy. We are using AUTO_VERSION (which is actually the problem, before we were generating the version before ourselves so we knew it). Now I don't know how to generate the version locally that got generated on the server. I'm not sure what you do for commit count, but it seems to be different locally vs on the build server. `--version=latest` has race conditions and wouldn't work for us as we can deploy to multiple environments at once (and they currently share a release bucket, but they don't need to, i suppose)

**Comment by bharendt** [comment]
True, maybe we could add something similar to the `upgrade` command that builds the release and deploys it in a single step (maybe something like `install [release]`).
But for now you could try maybe one of the following things:

There are two commit-count options for auto-versioning: `commit-count-all-branches` which can differ on the build host or `commit-count-branch` which in combination with `+branch` is always the same on the build host and on the host that starts the build. If you calculate your version as before you would be able calculate it then still if you are using auto-versioning, e.g. like this:

```bash
  NEW_VERSION="$(my_increase_version_script)"
  BRANCH=xyz
  mix edeliver build release --branch="$BRANCH" --auto-version=commit-count-all-branches+branch+revision
  COMMIT_COUNT="$(git rev-list --count "$BRANCH")"
  REVISION="$(git rev-parse --short "$BRANCH")"
  mix edeliver deploy release --version="${NEW_VERSION}+${COMMIT_COUNT}-${BRANCH}-${REVISION}"
```

The other option would be to use a temporary local release store. If there is only one release in it that is deployed without the need to pass the version as `--version=` option, e.g. like this:

```bash
#.deliver/config
ACTUAL_RELEASE_STORE="..."
RELEASE_STORE=${RELEASE_STORE:-$ACTUAL_RELEASE_STORE}
```

```bash
# remove
TMP_RELEASE_STORE="$(mktemp -d)"
RELEASE_STORE="$TMP_RELEASE_STORE" mix edeliver build release 
mix edeliver deploy release
```
But you would then need to upload the generated release to the actual release store later if you want to store the built releases.

**Comment by aaronjensen** [comment]
Thanks. I ended up going back to out own automatic versioning and the old two step build upgrade deploy upgrade. I had no end of problems getting it to work otherwise.

**Comment by aaronjensen** [comment]
update command seems to work great, thank you!
