### ISSUE TITLE
restart and migrations

### ISSUE THREAD

**Issue by gaynetdinov** [boldpoker/edeliver#81]
Hello. 

I've noticed that after `mix edeliver restart env` new migrations do not appear. 
Step-by-step:
- deploy release with a new migration
- run restart
- run migrate, response is `[]`
- run stop, then start
- run migrate, response is `response: [20160510210500]`

Probably it's not edeliver issue, but `exrm` one, but maybe you know some details about restarting an `exrm` release? Thanks for your help!

**Comment by bharendt** [comment]
Yes, unfortunately the exrm/relx [`restart`](https://github.com/bitwalker/exrm/blob/fa1d2c91cae167731a328102568d5ce6c71302ba/priv/rel/files/nodetool#L31) command [only restarts the applications on the node](http://erlang.org/doc/man/init.html#restart-0), without loading new code nor booting a new release:

> The system is restarted inside the running Erlang node, which means that the emulator is not restarted. All applications are taken down smoothly, all code is unloaded, and all ports are closed before the system is booted again in the same way as initially started. The same BootArgs are used again.

One option would be to map the edeliver `restart` command to the exrm/relx [`reboot` command](https://github.com/bitwalker/exrm/blob/fa1d2c91cae167731a328102568d5ce6c71302ba/priv/rel/files/nodetool#L33) which would restart the whole erlang vm, [but this works only if `-heart` is used](http://erlang.org/doc/man/init.html#reboot-0), which means that the external heart program needs to monitor the node and restart it whenever it is down.

> All applications are taken down smoothly, all code is unloaded, and all ports are closed before the system terminates. If the -heart command line flag was given, the heart program will try to reboot the system. Refer to heart(3) for more information.

I think we should change that quite soon, that the edeliver `restart` command restarts a node including the vm and boots the most recent release.

But at the moment you need to run `stop` and `start` as you figured out yourself.

**Comment by bharendt** [comment]
I think I will change it now, even if it is actually not backwards compatible. But it does not make sense for a deployment tool, that the `restart` command restarts the old release:

**Comment by gaynetdinov** [comment]
Thanks a lot!

**Comment by gaynetdinov** [comment]
I'm sorry I have to reopen the issue, because I used current master and still had the issue with `restart`.

**Comment by gaynetdinov** [comment]
How can I see which command were executed during `mix edeliver restart env`? --verbose, SILENT=false both don't work. `--debug` is too verbose and doesn't show which command got executed.

**Comment by bharendt** [comment]
No, actually there is no other option. `--verbose` prints the output for each executed command, but for node commands this is always true, so this does not make any different there. So `--debug` would be the right option because it shows any shell command executed or running. But true, it is very verbose and quite hard to interpret, maybe grepping for `start` might help.

Other things you could try might be:

 - verifying that the correct new edliver version `8b3137a` is used __locally__
 - checking whether the new version runs after restarting by using `edeliver version <env>`
 - by comparing the os pids of the erlang vm before restarting to check whether it was actually restarted

**Comment by gaynetdinov** [comment]
I added additional parameter to JSON response of my api in branch called `test`, then built a release and deployed it to qa1 env, then I ran `restart`. After that `version` command shows the correct version of the release deployed, but new parameter in the JSON response doesn't appear. After `restart` command PIDs are the same. After `stop/start` PIDs changed, new param appeared and everything worked as expected.

In my mix file I have
```
{:edeliver, github: "boldpoker/edeliver", ref: "8b3137a33503235cce881761805a295af3150319"},
```

In the mix.lock file
```
"edeliver": {:git, "https://github.com/boldpoker/edeliver.git", "8b3137a33503235cce881761805a295af3150319", [ref: "8b3137a33503235cce881761805a295af3150319"]},
```

Ah, found it! Ran with --debug:

```
++ [[ -n '' ]]
++ _config_arg=
++ '[' single_node '!=' single_node ']'
++ [[ -n '' ]]
++ _remote_job='
    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd /home/dashboard/qa//user_settings_service
    if [[ "restart | tail -n+2" = "restart" ]]; then
      bin/user_settings_service stop  && bin/user_settings_service start
    else
      bin/user_settings_service restart | tail -n+2
    fi
  '
++ '[' single_node = single_node ']'
++ local '_terminal_option=-t -q'
++ ssh -t -q -o ConnectTimeout=3 dashboard@qa-1.adjust.com '
    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd /home/dashboard/qa//user_settings_service
    if [[ "restart | tail -n+2" = "restart" ]]; then
      bin/user_settings_service stop  && bin/user_settings_service start
    else
      bin/user_settings_service restart | tail -n+2
    fi
  '
```

**Comment by bharendt** [comment]
Ah, I see. Thanks! Will fix that...

**Comment by bharendt** [comment]
Sorry, that last fix was maybe too quick and not tested. Forgot that the ` | tail -n+2` is appended to the node commands to hide output from exrm which shows the current version of the start script which is used. Hope it works now.

**Comment by gaynetdinov** [comment]
Yep, it works now, thanks. 

But the output now looks a bit verbose:

```
qa1 node:

  user    : dashboard
  host    : myhost
  path    : /home/dashboard/qa/
  response: Using /home/dashboard/qa/user_settings_service/releases/0.0.1+test-e441bb2/user_settings_service.sh
ok
Using /home/dashboard/qa/user_settings_service/releases/0.0.1+test-e441bb2/user_settings_service.sh

RESTART DONE!
```

**Comment by bharendt** [comment]
True, and the output of the stop command should only be visisble if it fails:

**Comment by bharendt** [comment]
Does it help? I can't test it right now

**Comment by gaynetdinov** [comment]
It still works, but now response is empty. 
```
qa1 node:

  user    : dashboard
  host    : myhost
  path    : /home/dashboard/qa/
  response:

RESTART DONE!
```

**Comment by bharendt** [comment]
I saw that already in your above output, that the `bin/$APP start` command does not return any output.  This is maybe on purpose, because the release is started detatched as a forked process, so the result of that operation cannot be determined. But maybe edeliver could return `restarted` in that case or `starting...`

**Comment by gaynetdinov** [comment]
Yeah, `ok` would make more sense to me, but someone might argue that since `edeliver` just returns a result from command executed on remote host, empty string also would make sense, since `start` command does not return anything.

**Comment by bharendt** [comment]
Yes. I also think returning nothing is quite confusing. One might think something went wrong or just nothing happened.

I think it would be even better to wait until the release is started in that case and only then return `ok`. Returning nothing and just hoping that the release started is not so reliable.

This could be maybe done by trying to ping the node after the start and if ping succeeded, monitor the startup progress on the node.

This might be not so easy to implement, but as a first step we could require that `edeliver` is added as last app in the `application` section of the `mix.exs`, which would mean that it is started as last application of the release. We could then wait until the `edeliver` app is running and then return `ok` for the `edeliver [re]start` command, indicating that all other apps for the release were started successfully.

**Comment by bharendt** [comment]
[This was added](https://github.com/boldpoker/edeliver/pull/86) in version `1.2.6`
