### ISSUE TITLE
status messages are not visible in light themes

### ISSUE THREAD

**Issue by gaynetdinov** [boldpoker/edeliver#84]
I've tried multiple light themes(pencil, material, solarized, paper, etc) and for every light theme status messages are either not visible at all or barely visible. 

Currently with solarized it looks like this:

![screen shot 2016-05-13 at 11 59 36](https://cloud.githubusercontent.com/assets/1541059/15244604/3147f70a-1902-11e6-8478-09ab4fd3fe4d.png)

Is there any way to configure the colour of the status messages?
Thanks!

**Comment by bharendt** [comment]
Yes, the colors are not adjusted to any theme. But I think you should be able to override the colors [which are used by edeliver](https://github.com/boldpoker/edeliver/blob/ed870313f3004d14ec2bf5380bdea99c943cdd73/libexec/output#L17-L32) in your `.deliver/config`, e.g. like this:

```bash
  txtwht=$(tput setaf 2) # use green text color instead of white 
  bldwht=${txtbld}${txtred} # use bold red color instead of bold white
```

This would be the most frequently used colors you might want to override:

```bash
$ grep -rhoe 'txt\w+\|bld\w\+' libexec/ strategies/ | sort | uniq -c | sort -rn
  68 bldwht
  24 bldylw
  14 bldgrn
   5 bldred
   2 bldmgt
   2 bldblu
   1 bldcyn
```

**Comment by gaynetdinov** [comment]
Thanks!

**Comment by gregpardo** [comment]
I also had this problem. Was having a difficult time debugging and I realized eventually I didn't have the output the way it was supposed to look.

**Comment by onelesd** [comment]
If you use iTerm you can set the minimum contrast for foreground & background colors.

<img width="603" alt="itermcolors" src="https://cloud.githubusercontent.com/assets/958603/21960500/3b48f25a-daa3-11e6-9c2c-b82141fb22d4.png">
