### ISSUE TITLE
Automating deployment with edeliver

### ISSUE THREAD

**Issue by pdilyard** [boldpoker/edeliver#85]
How would one go about automating deployment with edeliver? So far, my plan is this:

1. A commit is made on master
2. My CI server pulls down the most recent version of the project repository
3. The CI server will then build a release and push it to the staging environment using edeliver

Where I'm having trouble is with step 3. What if a new node is added to the cluster? It won't have a running version, so upgrading it would fail (unless edeliver handles this case; does it?). Live code reloading is important in my case, even (possibly especially) when adding nodes.

If this case is not handled by edeliver, what kind of approach should be taken here? Is there some sort of per-node check I can do to create a release for some nodes and an upgrade for others?

**Comment by bharendt** [comment]
If a node is added to the cluster this must be added to the `PRODUCTION_HOSTS` (or `STAGING_HOSTS` respectively) in your `.deliver/config` and you must deploy the release to that node and start it, e.g. like this:

```bash
edeliver deploy release to production --host=<new-host> --start-deploy
```

If new nodes are dynamically added, you could automate this e.g by fetching the list from a server:

```bash
PRODUCTION_HOSTS="$(curl my-service-discovery/production)"
STAGING_HOSTS"$(curl my-service-discovery/staging)"
```

When using exrm as build tool you can deploy the same upgrade tar which you would deploy also to the running nodes and which was built using the `edeliver build upgrade` command also as a "release" tar to start new nodes. If using another build tool you must build a separate release for it using `edeliver build release`.

But what you might want to use is the edeliver `upgrade` command. It automates this steps and does the following things:

 - checks that all running nodes run the same release version
 - builds an hot code upgrade from that version to the current (or what you pass as `--to=` option)
 - deploys that upgrade to that (running) nodes
 - deploys the release to not running nodes and starts them if you pass the `--start-deploy` option
 - validates that all nodes run the new release version

**Comment by pdilyard** [comment]
Hmm ok. I'll give it a go and document my experience here if you don't mind.

**Comment by bharendt** [comment]
Yes, of course. Let us know what worked out of the box and where you had some trouble. 
This feature is quite new (since `1.2.0`) and certenly could need some feedback.

**Comment by isaacsanders** [comment]
Does edeliver have a mechanism for connecting `n` nodes when deploying? I am trying to figure out how to perform such a deploy, and much googling has not helped.

**Comment by bharendt** [comment]
Edeliver does not provide such a feature, but erlang does. You have mainly two options: configure the [kernel application](http://erlang.org/doc/man/kernel_app.html) to auto-connect to other nodes and (if you want) wait until they are available (`sync_nodes_mandatory` and `sync_nodes_optional` configuration). The other option is to connect manually to another node e.g. by using `:net_adm.ping(node)`. This can be done either in your application code, while your application is starting, or triggered by an edeliver `post_start_deployed_release` [post hook](https://github.com/boldpoker/edeliver/wiki/Run-additional-build-tasks) using and rpc call to your node when the application was deployed (see also #114).
