### ISSUE TITLE
Too long build task

### ISSUE THREAD

**Issue by insiderq** [boldpoker/edeliver#89]
Is there a way to edeliver not to recompile all dependencies every time it's used?

**Comment by bharendt** [comment]
Yes. You can use the `--skip-git-clean` option to keep everything from the last build, which means also the dependencies or even the `--skip-mix-clean` option for incremental builds. You also can adjust the `GIT_CLEAN_PATHS` env then in your `.deliver/config` to keep only the dependencies. You can find more information [about faster builds here](https://github.com/boldpoker/edeliver/wiki/Faster-builds), in the [wiki](https://github.com/boldpoker/edeliver/wiki/Faster-builds).

**Comment by insiderq** [comment]
What a great response, despite the fact that i should've found this by myself. Thanks a lot!
