### ISSUE TITLE
Deploy notifications

### ISSUE THREAD

**Issue by gaynetdinov** [boldpoker/edeliver#97]
Hello. 

I need to send a notification about deployment: one notification just before deployment and one notification after deployment(for different purposes, for example for slack notifications). Fortunately `edeliver` has some hooks for exactly this purposes. 

But for a notification itself I need to know git user, revision, branch and environment. With capistrano-like deployment tools all these parameters can be extracted during deployment on target host. However in case of `edeliver` it's possible that somebody is gonna deploy a release which was built by someone else. And there is no way to run any `git` related command since release is just a binary. 

So I came up with the following solution: I set `AUTO_VERSION=git-branch+git-revision` so a release contains git branch and revision in its name and I implemented upgrade hooks like this:

```sh
pre_upgrade_release() {
  status "Sending 'deploying' notification"
  local _username=$(git config user.name)

  if [[ "$DEPLOY_ENVIRONMENT" = "production" ]]; then
    TARGET_FOLDER="$DELIVER_TO"
  else
    TARGET_FOLDER="$TEST_AT"
  fi

  __sync_remote "
    [ -f ~/.profile ] && source ~/.profile
    set -e

    # split version by '+' sign, first element would be a release version
    # second element is a string 'branch-name-revision'
    IFS='+' read -a array <<< '$VERSION'
    IFS='-' read -a new_array <<< \"\${array[1]}\"

    # revision is the last element in the array
    revision=\"\${new_array[-1]}\"

    # remove revision from the array
    unset new_array[${#new_array[@]}-1]

    # join rest elements in the array into a string
    # using '-' as delimeter
    IFS=-
    branch_name=\"\${new_array[*]}\"

    cd '$TARGET_FOLDER/$APP'
    ./bin/my_app rpc Elixir.MyApp.Notification deploying \"[<<\\\"$_username\\\">>, <<\\\"\$branch_name\\\">>, <<\\\"\$revision\\\">>, <<\\\"$DEPLOY_ENVIRONMENT\\\">>].\" >/dev/null
  "
}
```
`post_upgrade_release` hook is exactly the same, the only difference is the last line, where instead of calling `deploying` function I call `deployed`. 

This solution works, but it's obviously suboptimal. 

1. I couldn't extract the common part of `pre_upgrade_release` and `post_upgrade_release` functions into one function due to lack of bash knowledge. For example I'd love to have a function which would return branch and revision, so I could use them in both hooks. 
2. Maybe there is a better way? Since `mix edeliver version production` shows commits, there must a way to get git related data from a release, right? 

Could you please suggest any improvements regarding this approach? 

Thank you so much!

**Comment by bharendt** [comment]
You coud for example move the version parsing code from bash to elixir by calling the [Edeliver.release_version/1](https://hexdocs.pm/edeliver/Edeliver.html#release_version/2) like that:

```elixir
defmodule MyApp.Notification do

  def send(deploy_user, deploy_environment, finished) do
    {revision, branch} = 
      :your_app 
      |> Edeliver.release_version() 
      |> to_string() 
      |> extract_git_info_from_release_version()
    send_notification "#{deploy_user} deploy#{finished && "ed" || "s"} #{revision} from #{branch} to #{deploy_environment}"
  end

  # ...
end
```

and then call the `Elixir.MyApp.Notification/3` function from the hooks which would have a little less code:

```bash
pre_upgrade_release() {
  status "Sending 'deploying' notification"
  send_deploy_notification "false"
}

post_upgrade_release() {
  status "Sending 'deployed' notification"
  send_deploy_notification "true"
}

send_deploy_notification() {
  local _finished="$1"
  local _username=$(git config user.name)

  __sync_remote "
    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd '$DELIVER_TO/$APP'
    ./bin/$APP rpc Elixir.MyApp.Notification send \"[<<\\\"$_username\\\">>, <<\\\"$DEPLOY_ENVIRONMENT\\\">>, \$_finished].\" >/dev/null
  "}

```

Note: `DELIVER_TO` should be set to `TEST_AT` [already for staging environment](https://github.com/boldpoker/edeliver/blob/4de6d7dcb2738dd311f4b7c31033b88eacd07db0/libexec/erlang#L47).

**Comment by gaynetdinov** [comment]
Ah, this is so much nicer! Thank you!
