### ISSUE TITLE
Including non-Elixir dependencies in the release

### ISSUE THREAD

**Issue by onelesd** [boldpoker/edeliver#98]
I have a legacy Perl script (in bin/ of my repo) which has some CPAN dependencies. My Elixir project uses porcelain to pass data with the Perl script. As an additional build step I install those dependencies (into perl_modules/), however the script and deps are not included in the release.

What is the proper way to include non-elixir dependencies in a release?

```
pre_erlang_clean_compile() {
  status "Installing Perl dependencies for urldecoder" # log output prepended with "----->"
  __sync_remote " # runs the commands on the build host
    [ -f ~/.profile ] && source ~/.profile # load profile (optional)
    set -e # fail if any command fails (recommended)
    cd '$BUILD_AT' # enter the build directory on the build host (required)
    # run your custom task
    ./bin/perldeps
  "
}
```

**Comment by bharendt** [comment]
To include them into the built release, they must be copied to `$BUILD_AT/priv` on the build host in the `pre_erlang_clean_compile` hook. The `priv` directory can then be determined in the running release using the [`:code.priv_dir(:your_app)`](http://erlang.org/doc/man/code.html#priv_dir-1) erlang function.

**Comment by onelesd** [comment]
This worked. Thank you!
